<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Imagens</name>
   <tag></tag>
   <elementGuidId>b078cba3-d3a2-43ba-82f7-2e6c9042c966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.hdtb-mitem > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-msb']/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1abbfa54-b5b8-4c7b-8c35-1b2dc2ef4cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=hollywood&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;hl=pt-PT&amp;biw=1536&amp;bih=754&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwja5tWMq7T-AhUSOcAKHTiQDOkQ_AUoAXoECAEQAw</value>
      <webElementGuid>4eb7749e-0217-4ed4-8d25-d0bfd6cd0286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hveid</name>
      <type>Main</type>
      <value>CAEQAw</value>
      <webElementGuid>1bf5f655-accc-485c-94a7-f4d99441869c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imagens</value>
      <webElementGuid>11d897f2-b894-4dac-b9c5-7d171b2f1635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-msb&quot;)/div[1]/div[@class=&quot;MUFPAc&quot;]/div[@class=&quot;hdtb-mitem&quot;]/a[1]</value>
      <webElementGuid>7fb97d57-c7e4-4efb-b8c1-61e6f79bb7ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-msb']/div/div/div[2]/a</value>
      <webElementGuid>614d8ad8-3048-4817-ad55-6fe47b48a462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Imagens')]</value>
      <webElementGuid>c9f4223c-4b98-4256-86a1-ff4c663c3d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tudo'])[1]/following::a[1]</value>
      <webElementGuid>c100b906-f19b-42b2-807d-240d28707ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modos de pesquisa'])[1]/following::a[1]</value>
      <webElementGuid>ad7aadf3-5a80-410b-9494-ce66ddbfd5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vídeos'])[1]/preceding::a[1]</value>
      <webElementGuid>26703f79-1d7f-4470-886c-735225c57b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notícias'])[1]/preceding::a[2]</value>
      <webElementGuid>6a4cb4a7-f323-453b-9c69-5a817fb6b586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Imagens']/parent::*</value>
      <webElementGuid>7dd599e9-b5e4-42d6-a5d5-cce543a358d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?q=hollywood&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;hl=pt-PT&amp;biw=1536&amp;bih=754&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwja5tWMq7T-AhUSOcAKHTiQDOkQ_AUoAXoECAEQAw')]</value>
      <webElementGuid>07dbc3e3-6966-4bf9-835b-35cacad4aa30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>a3f43a65-35f9-4e0f-a51b-1b3acb4cbb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=hollywood&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;hl=pt-PT&amp;biw=1536&amp;bih=754&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwja5tWMq7T-AhUSOcAKHTiQDOkQ_AUoAXoECAEQAw' and (text() = 'Imagens' or . = 'Imagens')]</value>
      <webElementGuid>3741371b-9f11-494c-823e-eeb6a51365d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
