<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vdeos</name>
   <tag></tag>
   <elementGuidId>39ae3e3e-cdee-402e-8e26-5fc93eb91566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-msb']/div/div/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb40abc6-9c15-4734-a23c-e7f32d23e08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=hollywood&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;hl=pt-PT&amp;biw=1536&amp;bih=754&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwja5tWMq7T-AhUSOcAKHTiQDOkQ_AUoAnoECAEQBA</value>
      <webElementGuid>d8fc32de-32a3-4009-9483-167a3d840916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hveid</name>
      <type>Main</type>
      <value>CAEQBA</value>
      <webElementGuid>8126bf6b-21c8-4891-8a1e-e4303cfcddc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vídeos</value>
      <webElementGuid>3b28f60b-6104-4b60-a0ac-8cd5330d16a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-msb&quot;)/div[1]/div[@class=&quot;MUFPAc&quot;]/div[@class=&quot;hdtb-mitem&quot;]/a[1]</value>
      <webElementGuid>20196057-46f0-41a0-8835-931fe488334d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-msb']/div/div/div[3]/a</value>
      <webElementGuid>4c26a309-061f-4163-b092-59b1b61fbb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vídeos')]</value>
      <webElementGuid>cec1d574-5e10-4d16-8f51-4ac075907544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imagens'])[1]/following::a[1]</value>
      <webElementGuid>3b8fdf02-864b-452f-8dea-6cd7e911169b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tudo'])[1]/following::a[2]</value>
      <webElementGuid>fd39deda-5efe-4343-b03b-29c5e9cac549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notícias'])[1]/preceding::a[1]</value>
      <webElementGuid>0f6ad882-c058-423f-9eb9-06a4e5ad6f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maps'])[1]/preceding::a[2]</value>
      <webElementGuid>36ad4280-7441-4594-ae2c-dfa1651a92c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vídeos']/parent::*</value>
      <webElementGuid>06a815f2-b447-493e-8abd-c16d326da547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?q=hollywood&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;hl=pt-PT&amp;biw=1536&amp;bih=754&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwja5tWMq7T-AhUSOcAKHTiQDOkQ_AUoAnoECAEQBA')]</value>
      <webElementGuid>037da206-0c5c-4825-9cba-f6c504c95290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/a</value>
      <webElementGuid>fa1994a0-4f82-4dfb-85fb-c142d1810575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=hollywood&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;hl=pt-PT&amp;biw=1536&amp;bih=754&amp;source=lnms&amp;tbm=vid&amp;sa=X&amp;ved=2ahUKEwja5tWMq7T-AhUSOcAKHTiQDOkQ_AUoAnoECAEQBA' and (text() = 'Vídeos' or . = 'Vídeos')]</value>
      <webElementGuid>7c513320-2bf4-4def-90f8-704136d6b0a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
