<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tudo</name>
   <tag></tag>
   <elementGuidId>0c275845-f3e8-44cd-92c6-2911edeeba1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.hdtb-mitem.hdtb-msel > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-msb']/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa126523-7a3d-4b69-b52b-b10f02302d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tudo</value>
      <webElementGuid>e88c2203-3c6c-4231-a9b0-5e59d7c274fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-msb&quot;)/div[1]/div[@class=&quot;MUFPAc&quot;]/div[@class=&quot;hdtb-mitem hdtb-msel&quot;]/span[1]</value>
      <webElementGuid>e1e3a044-9b77-43c1-ad6c-8ed41ffd4916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-msb']/div/div/div/span</value>
      <webElementGuid>e8f6db5a-1450-4465-abd7-9e5d1966c1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modos de pesquisa'])[1]/following::span[1]</value>
      <webElementGuid>0e7f1dd3-ca8d-4605-b3df-dd28b6e17722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar'])[1]/following::span[2]</value>
      <webElementGuid>1d190d71-f5be-47f8-a42d-1d56a21db4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imagens'])[1]/preceding::span[2]</value>
      <webElementGuid>6130243d-2137-421a-835e-e6ed5741ca40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vídeos'])[1]/preceding::span[3]</value>
      <webElementGuid>afa2b00c-5ca9-484a-b3cc-fe20f33b0f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tudo']/parent::*</value>
      <webElementGuid>2d440c3d-52cf-41cd-9e53-b6a9a06b574d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div/div/div/div/span</value>
      <webElementGuid>243031a0-09f7-49ff-92fa-7bd1e70ce860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tudo' or . = 'Tudo')]</value>
      <webElementGuid>57e1171e-76c7-4ad9-9621-990ceca29a47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
