<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>557ba8a7-27d8-4014-b671-335f55922f7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='top']/div/div[2]/div[2]/div/div/nav[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.go-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>007f0080-b4f2-477b-8af6-119544122938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pesquisar/</value>
      <webElementGuid>4b0a96ec-e8b2-4850-93f6-cce9dbd3d0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>go-search</value>
      <webElementGuid>cfafe22a-935f-46f1-a212-8f38ffbced4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>d7bf6303-cd0a-4a83-b76e-0c678a567260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container py-1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 col-sm-8 col-md-9 text-right&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 justify-content-end my-md-0 align-items-center d-flex&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light align-items-center hamburguer-container d-flex col-12 col-xl-2 justify-content-end&quot;]/div[@class=&quot;top-search&quot;]/a[@class=&quot;go-search&quot;]</value>
      <webElementGuid>08633d33-dce8-419f-a68e-87631d53ec56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='top']/div/div[2]/div[2]/div/div/nav[2]/div/a</value>
      <webElementGuid>708ed335-64ef-41e0-a8f9-2e41f8b95080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TV Zimbo'])[2]/following::a[1]</value>
      <webElementGuid>6ffb84cb-b429-4fa1-bed1-9f44abc334f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programação'])[1]/following::a[2]</value>
      <webElementGuid>cb1654f5-ae45-4d0a-9f56-1f79e2eb6e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Início'])[2]/preceding::a[2]</value>
      <webElementGuid>53f56b35-c4b9-435a-8709-929d0552622b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informação'])[2]/preceding::a[3]</value>
      <webElementGuid>d1d8865a-09a9-49bf-b552-83d6facdac10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pesquisar/')]</value>
      <webElementGuid>ac6292f2-dc63-4302-8381-c4d473c11e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/div/a</value>
      <webElementGuid>29e50768-61ec-43d8-b091-3d58cc557e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pesquisar/' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>cb400014-e593-472d-8ca8-ce0b7558a922</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
