<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Entretenimento</name>
   <tag></tag>
   <elementGuidId>86591c3d-9135-44b2-a165-dbc6f37e359a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='top']/div/div[2]/div[2]/div/div/nav/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2ada210-88b9-463d-8f60-4deab5c0ab9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>517a5d90-994c-4b54-80a7-9f49cecd53a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ao/entretenimento/</value>
      <webElementGuid>c5d6e661-1c9b-4de0-8ead-29963fb5b7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entretenimento</value>
      <webElementGuid>4cbdb19c-0cd6-4bea-b496-7f9b1e6b259f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container py-1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 col-sm-8 col-md-9 text-right&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 justify-content-end my-md-0 align-items-center d-flex&quot;]/nav[@class=&quot;navbar navbar-expand-xl navbar-light menu-top-container d-none d-xl-flex col-xl-10&quot;]/ul[@class=&quot;navbar-nav ml-auto menu-topo&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>4ebd6d46-255f-4ca0-b125-7c436814aff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='top']/div/div[2]/div[2]/div/div/nav/ul/li[3]/a</value>
      <webElementGuid>6f736667-b58a-4848-b2f5-e4391e92150f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entretenimento')]</value>
      <webElementGuid>e0198c31-8599-42ab-904f-7860616cad73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informação'])[1]/following::a[1]</value>
      <webElementGuid>835ab363-7d0d-4bac-901d-d06cd73834b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Início'])[1]/following::a[2]</value>
      <webElementGuid>a096756f-1174-40d7-81ec-d70aaae35e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbo Online'])[1]/preceding::a[1]</value>
      <webElementGuid>82a0b980-2741-4f22-9509-4172635e945b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programação'])[1]/preceding::a[2]</value>
      <webElementGuid>b636c7db-f112-407a-920d-0e9b71f8b4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entretenimento']/parent::*</value>
      <webElementGuid>1e27f952-de57-432f-80a0-cee3220626a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ao/entretenimento/')]</value>
      <webElementGuid>83e52497-dd58-4757-a6e6-3e754f0de43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>36168915-253f-4bf5-8618-9ce37a7c91f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ao/entretenimento/' and (text() = 'Entretenimento' or . = 'Entretenimento')]</value>
      <webElementGuid>f843af6b-0669-4b46-b33f-2ececf83a915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
