<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Informao</name>
   <tag></tag>
   <elementGuidId>0e07cfe2-46e0-415b-a01e-c849efbfbefa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='top']/div/div[2]/div[2]/div/div/nav/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fe76eec-eb5d-4bb6-af68-27d86c7addc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>7e24e5b4-d418-4ec2-a4cf-f852eb0be7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ao/informacao/</value>
      <webElementGuid>f86aa18b-eec5-4d4c-9205-7d2f3a6b4791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informação</value>
      <webElementGuid>236d53c8-b25f-4bec-8d89-3b3dbb40168f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;container py-1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 col-sm-8 col-md-9 text-right&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 justify-content-end my-md-0 align-items-center d-flex&quot;]/nav[@class=&quot;navbar navbar-expand-xl navbar-light menu-top-container d-none d-xl-flex col-xl-10&quot;]/ul[@class=&quot;navbar-nav ml-auto menu-topo&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>20ea9786-e4ab-4067-b970-64ac20c176cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='top']/div/div[2]/div[2]/div/div/nav/ul/li[2]/a</value>
      <webElementGuid>6d9d71cb-9a63-4428-98d3-45d271b83398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Informação')]</value>
      <webElementGuid>6184c96c-5e54-4f8c-8d8e-3f4f61ab4340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Início'])[1]/following::a[1]</value>
      <webElementGuid>3c97e283-c6d4-4c49-8daa-ab81280c68f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entretenimento'])[1]/preceding::a[1]</value>
      <webElementGuid>031fa3ec-0d6c-4206-b513-704f3a47ace1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbo Online'])[1]/preceding::a[2]</value>
      <webElementGuid>0737a731-8b5c-408f-a6ef-037d5cf3b520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Informação']/parent::*</value>
      <webElementGuid>4b553c42-e8f1-49b6-b71b-f9cc7272db81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ao/informacao/')]</value>
      <webElementGuid>169bfe47-dcdc-454f-ac39-a466a91f9be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>86165196-6805-491c-8d13-9e20abeb5cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ao/informacao/' and (text() = 'Informação' or . = 'Informação')]</value>
      <webElementGuid>ce4acd4d-b7ca-4e9e-b65c-96775ff2da68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
