<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_bom morar em Luanda_L3Ezfd</name>
   <tag></tag>
   <elementGuidId>5b4cebd9-cbde-49e1-bef9-02c8fb22bbff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DjZBZIeGDq_c7_UPvPud-As__214']/div/div/div[2]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.L3Ezfd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8aa4bb6-b37f-4a3c-b0e2-c4aa900070d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>pcRaIe</value>
      <webElementGuid>724ea6e7-a395-40eb-a682-9e55f80d71d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>L3Ezfd</value>
      <webElementGuid>c39b9010-3c2a-4aac-aa9b-4743ed5f726c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwiHxcrYwLj-AhUv7rsIHbx9B78Quk56BAhWEAI</value>
      <webElementGuid>d0c3fd44-9fce-4b91-8296-40b812cb39e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DjZBZIeGDq_c7_UPvPud-As__214&quot;)/div[@class=&quot;wQiwMc related-question-pair&quot;]/div[@class=&quot;HYvwY ilulF roMIYb oST1qe g7pt6d h373nd&quot;]/div[2]/div[@class=&quot;dnXCYb&quot;]/div[@class=&quot;L3Ezfd&quot;]</value>
      <webElementGuid>d72054b6-eb4e-4d8b-ab21-a69f1e3f66cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DjZBZIeGDq_c7_UPvPud-As__214']/div/div/div[2]/div/div[3]</value>
      <webElementGuid>e8b17697-4fa5-4418-9ae7-0b0434aff082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div[3]</value>
      <webElementGuid>95c36cfa-7b16-4d3a-bcdd-93851542a6b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
