<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ID_utilizador</name>
   <tag></tag>
   <elementGuidId>fed6dddd-2132-4d0b-8cc3-fbba43303579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#j_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='j_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d57730a0-13ea-459a-8a7f-81e8ce13d063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_username</value>
      <webElementGuid>514a9045-efd8-4d26-be7b-99da814552dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_username</value>
      <webElementGuid>bfd706d4-2f91-42cf-9494-eb21b8162563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cae9ee63-f8c4-4f2a-a04d-de34a39b8934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1b5e2c72-cd88-4c9f-b6e5-69c38ed2a982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ID Utilizador</value>
      <webElementGuid>877c7286-cf6c-42ff-907f-075afd00540e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_username&quot;)</value>
      <webElementGuid>d60e78a1-909e-406f-ad78-9bf4cdd5aa3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='j_username']</value>
      <webElementGuid>8b4239cd-5786-4cd2-ac58-5e7ddae73bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/main/form/div/div/input</value>
      <webElementGuid>043eba47-1c03-4fbf-ae38-ac7d4356a515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fdf99126-052b-4507-952e-8fdcfdb782b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'j_username' and @name = 'j_username' and @type = 'text' and @placeholder = 'ID Utilizador']</value>
      <webElementGuid>c988a539-f8cb-4cfe-a34f-18e742e25647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
