<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Opinio</name>
   <tag></tag>
   <elementGuidId>c81b8912-08e2-488c-8087-fc2d79d80a2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-45 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-45']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0edaae52-3feb-44d3-8aa7-f80a97d41311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://jornalf8.net/category/opiniao/</value>
      <webElementGuid>56882070-7ada-4d61-8080-a10813da076c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Opinião</value>
      <webElementGuid>faa4100f-fb94-4c3d-90fc-ef1cd6e30a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-45&quot;)/a[1]</value>
      <webElementGuid>df7d8d2d-0a61-40a0-af3f-8feee1d26be1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-45']/a</value>
      <webElementGuid>a72df5f9-59af-4026-93f1-2b37418528a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Opinião')]</value>
      <webElementGuid>ee512196-b345-4f8d-aacd-6c6f3d006073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sociedade'])[1]/following::a[1]</value>
      <webElementGuid>1ed65dcc-fb56-4b14-b481-c199cd62210e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desporto'])[1]/following::a[2]</value>
      <webElementGuid>33231dca-2c26-4a13-8b0e-5afb98fa64a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Economia'])[1]/preceding::a[1]</value>
      <webElementGuid>1f87e6e1-c1ce-4281-a2dc-128accd7cd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cultura'])[1]/preceding::a[2]</value>
      <webElementGuid>02707f21-d385-492d-b973-40889345b49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Opinião']/parent::*</value>
      <webElementGuid>4fec3a53-151c-463f-b311-ac4e143e8e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://jornalf8.net/category/opiniao/')]</value>
      <webElementGuid>5b00b88f-8de0-4311-9698-1b910abc12c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/a</value>
      <webElementGuid>b77a1807-beb7-4c36-b9c0-77f8f55169d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://jornalf8.net/category/opiniao/' and (text() = 'Opinião' or . = 'Opinião')]</value>
      <webElementGuid>e0b266e5-1348-4f1f-91a4-ae44588ab62d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
