<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_loopa_Declarante</name>
   <tag></tag>
   <elementGuidId>6cf3944e-0d10-4956-8545-ef61ca548fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmPatrimony:tvSuporte:accPrincipal:btnSerchPerson1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-button-icon-left.ui-icon.ui-c.fa.fa-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d297b0a7-2d01-4160-8b3e-73bf0b9d4267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon-left ui-icon ui-c fa fa-search</value>
      <webElementGuid>1fd77d28-307e-4fb8-9ee0-5e20340f4357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:btnSerchPerson1&quot;)/span[@class=&quot;ui-button-icon-left ui-icon ui-c fa fa-search&quot;]</value>
      <webElementGuid>9588b0dd-3768-4033-b5d4-deddaaa5faa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='frmPatrimony:tvSuporte:accPrincipal:btnSerchPerson1']/span</value>
      <webElementGuid>34adbb53-0cca-47d1-b9c0-874e5a458469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>575a56ac-b103-4e03-b037-be8d53202507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
