<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deletar_Valor Declarado (Kz)_frmPatrimonytvSuporteaccPrincipaldeclaredValue_input</name>
   <tag></tag>
   <elementGuidId>0134c247-4882-43fa-9548-406b2b802eed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c96f7cd6-9179-4abe-87d4-83bbefd29e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:declaredValue_input</value>
      <webElementGuid>70a8f3fe-cc5e-4995-aa3b-dbbfa402887f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:declaredValue_input</value>
      <webElementGuid>49465684-e0ae-4f90-bc00-281b11e2b0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>069be09b-2d58-4d78-ae8a-1405896b0a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f5135d4-bf6b-4a03-ba7c-7341b1eb69e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;frmPatrimony:tvSuporte:accPrincipal:declaredValue&quot;,e:&quot;valueChange&quot;,p:&quot;frmPatrimony&quot;,u:&quot;frmPatrimony&quot;});</value>
      <webElementGuid>bfabcc4c-f82d-4c37-b541-15f7a973e969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>72dd9f7d-420b-46d5-bcef-180960482092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-con</name>
      <type>Main</type>
      <value>javax.faces.BigDecimal</value>
      <webElementGuid>392d0d77-64f0-4d16-9c3b-73c0d121d122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-hl</name>
      <type>Main</type>
      <value>inputnumber</value>
      <webElementGuid>9a7bd5b2-5776-495f-82d9-7c8c0a5d5bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d5c4eee1-a59d-4a59-8bf8-e79d93139cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1003c89b-ea5f-4777-ab05-27e7f892d222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ff9c73c-b283-4138-a2c6-adc13ed1c11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:declaredValue_input&quot;)</value>
      <webElementGuid>9a6eef39-befd-4c6c-a8ee-5765e379d326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue_input']</value>
      <webElementGuid>016ac7e4-3d70-4ac6-9389-25db5d6bf7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue']/input</value>
      <webElementGuid>e79bceec-3592-43b3-9ff9-15319f8feaad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[8]/div/span/input</value>
      <webElementGuid>b7ac2353-1eee-4f3a-85cf-8bca89a531a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPatrimony:tvSuporte:accPrincipal:declaredValue_input' and @name = 'frmPatrimony:tvSuporte:accPrincipal:declaredValue_input' and @type = 'text']</value>
      <webElementGuid>5e628293-9d74-49a0-a43e-8f41befbd72d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
