<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete__Valor Declarado (Kz)_frmPatrimonytvSuporteaccPrincipaldeclaredValue_input</name>
   <tag></tag>
   <elementGuidId>89345f1c-b5be-4f24-acfe-96055a0113cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8609605-213a-46d1-9c2c-fd34bfa42e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:declaredValue_input</value>
      <webElementGuid>506bc3be-2d91-45c3-b88f-169f73182976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:declaredValue_input</value>
      <webElementGuid>e3f895ab-8573-4a2f-bd2a-a32e023a5f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>52f6cff7-479a-4cf7-851e-d902c3ac9b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dc39e7e0-43ae-45d9-85ca-72674d34dace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;frmPatrimony:tvSuporte:accPrincipal:declaredValue&quot;,e:&quot;valueChange&quot;,p:&quot;frmPatrimony&quot;,u:&quot;frmPatrimony&quot;});</value>
      <webElementGuid>89629f98-3d72-471e-9d7f-29ce1384e966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>ec51a69e-5973-4422-b862-ab7b05f521e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-con</name>
      <type>Main</type>
      <value>javax.faces.BigDecimal</value>
      <webElementGuid>35f058f9-1684-4ec6-b5f2-6af4c682d08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-hl</name>
      <type>Main</type>
      <value>inputnumber</value>
      <webElementGuid>9c2a2c4e-6d90-4d88-97a8-cc226f9e51ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>edb3f2f1-3d59-44f4-8722-ff8ba3640aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>be1efd9b-187d-4d14-b02e-3e841428b588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a88a2c4f-4e65-46ec-bee3-25f6ba3ec225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:declaredValue_input&quot;)</value>
      <webElementGuid>ca57ad12-b7e6-4a9e-8ddb-9ecd2aa71f1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue_input']</value>
      <webElementGuid>fe870029-eb07-4100-9015-4d571ac1ded1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue']/input</value>
      <webElementGuid>c4cffd4e-3322-43c6-9458-69acc98da97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[8]/div/span/input</value>
      <webElementGuid>eb23bc6d-68c0-4794-8cbd-a61c94b060e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPatrimony:tvSuporte:accPrincipal:declaredValue_input' and @name = 'frmPatrimony:tvSuporte:accPrincipal:declaredValue_input' and @type = 'text']</value>
      <webElementGuid>dbf56f6a-b7bd-41d0-ac93-b25debb0e51e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
