<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nome da Propriedade_frmPatrimonytvSuporteaccPrincipalpropertyName (1)</name>
   <tag></tag>
   <elementGuidId>7c267b0d-5025-4e26-9bed-b3bd4d466984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:propertyName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc99c9b5-37cf-439e-84c9-0e2741df7449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:propertyName</value>
      <webElementGuid>bf132f00-1e6c-488a-ac2f-dafbbade4b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:propertyName</value>
      <webElementGuid>045212c1-5036-40db-84c1-a6cc90fd157d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>560a1ca5-2c15-4e35-a265-4b90af785683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all full-width ui-state-hover ui-state-focus</value>
      <webElementGuid>9d1098d7-23c4-45ac-b3e8-b2d7da45f51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>aadfd35f-f4b1-4897-9b1c-e87fcbf7bd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc987506-000c-4a54-b2c2-5244652c7f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8eb6c3d2-f28a-450b-b345-2261327c5a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:propertyName&quot;)</value>
      <webElementGuid>3416cf0f-96f1-483f-804a-149db4411b1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:propertyName']</value>
      <webElementGuid>51decfc9-bbe5-4e29-8ce0-fa6aa72a75ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPatrimony:tvSuporte:accPrincipal:j_id_75']/div/div/div/input</value>
      <webElementGuid>50253e49-b623-4f95-8f8f-51ae26189647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>8f43325d-34d3-43a0-bd84-0a30c8e5cadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPatrimony:tvSuporte:accPrincipal:propertyName' and @name = 'frmPatrimony:tvSuporte:accPrincipal:propertyName' and @type = 'text']</value>
      <webElementGuid>c9a74021-81f8-4262-b4c0-561c552b6038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
