<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nome do Contribuinte_frmSearchNIFBranchedialogSearchNIF-nameInput</name>
   <tag></tag>
   <elementGuidId>a8d78795-9e8a-41f4-8184-37937d3255a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmSearchNIFBranche:dialogSearchNIF-nameInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac1dc3c3-bd7c-4ba0-81ed-4863eee06a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmSearchNIFBranche:dialogSearchNIF-nameInput</value>
      <webElementGuid>74f2b412-2d7d-4770-896e-b593846c8d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmSearchNIFBranche:dialogSearchNIF-nameInput</value>
      <webElementGuid>adf5711b-7568-409b-8943-d88f3de5b2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e2fa8dbd-5ab4-4f83-abfe-8ae87aa95683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all form-control ui-state-focus ui-state-hover</value>
      <webElementGuid>b3b1cb11-eb2a-4ccd-9d2d-e5d5ca4d2a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>675ccd2d-e5e9-4f7e-a0ea-fd32658259ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ba2fd7f9-917f-4e31-8445-a6f68401a4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b976c0f-152e-47f4-ae4e-f874302c317a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSearchNIFBranche:dialogSearchNIF-nameInput&quot;)</value>
      <webElementGuid>dd4f6efe-3e37-462c-af57-a45be0b48cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmSearchNIFBranche:dialogSearchNIF-nameInput']</value>
      <webElementGuid>335a85c2-bb74-4a9a-9a65-d17180889cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSearchNIFBranche']/div/div/input</value>
      <webElementGuid>f6132ba5-a546-4bad-bab1-a18e9a4fe1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>c50a90cd-82ab-43f7-bee2-470368c55d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmSearchNIFBranche:dialogSearchNIF-nameInput' and @name = 'frmSearchNIFBranche:dialogSearchNIF-nameInput' and @type = 'text']</value>
      <webElementGuid>3d046f9c-44b3-477a-9280-0bc73a7254f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
