<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nome do Contribuinte_frmSearchNIFBranchedialogSearchNIF-nameInput</name>
   <tag></tag>
   <elementGuidId>3b828ac6-c607-42db-82cb-a05d49738548</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmSearchNIFBranche:dialogSearchNIF-nameInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7b53d65-588e-4daf-a5c0-e8107594d5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmSearchNIFBranche:dialogSearchNIF-nameInput</value>
      <webElementGuid>ae9feb72-3175-45a4-873d-27fb4904db84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmSearchNIFBranche:dialogSearchNIF-nameInput</value>
      <webElementGuid>7825529a-4f39-4f41-bce0-f8e885f31f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67a3c8e7-d4f9-4d8b-b0a8-6f006d558f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all form-control ui-state-focus ui-state-hover</value>
      <webElementGuid>d218554e-e9e3-468b-81ad-cba2c7dd7331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>842a3f99-5ef1-417d-81cb-436b2dc336ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4076087c-a963-492e-be88-021c5208f72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>04fbeebe-d024-434a-8262-232ecaca0efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSearchNIFBranche:dialogSearchNIF-nameInput&quot;)</value>
      <webElementGuid>a402cabe-652e-46ee-a45b-b9ff73feb277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmSearchNIFBranche:dialogSearchNIF-nameInput']</value>
      <webElementGuid>d1e60ad0-20b7-43aa-8e07-b0034a1f4249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSearchNIFBranche']/div/div/input</value>
      <webElementGuid>3e670e5b-3cac-4299-9e48-a443b1e085d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>5da91fcd-934a-457d-a3ae-71d4eed1f0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmSearchNIFBranche:dialogSearchNIF-nameInput' and @name = 'frmSearchNIFBranche:dialogSearchNIF-nameInput' and @type = 'text']</value>
      <webElementGuid>c8810578-50cf-4929-bf55-553231dfc5e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
