<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tcnico de Impostos</name>
   <tag></tag>
   <elementGuidId>2a04e60a-6fe9-4128-ac00-50259f793c37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='frmPatrimony:tvSuporte:accPrincipal:behalfOf_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f3ad35b8-61ac-458c-8a88-a7991eba471e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all</value>
      <webElementGuid>9c59647f-00c7-4960-8a27-99cd6ca53c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Técnico de Impostos</value>
      <webElementGuid>0a6a1c89-84eb-4cad-8835-f8fb684c1c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d2f95b29-d38d-4565-9af3-f5c559718e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2827a3e8-eb56-4f9c-b3fb-28e0135f571b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:behalfOf_4</value>
      <webElementGuid>3057821f-df45-458f-96fa-f770f6f3f052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Técnico de Impostos</value>
      <webElementGuid>6b937fde-90b2-440f-b780-25dee9be7966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:behalfOf_4&quot;)</value>
      <webElementGuid>7b9a9175-9764-4c20-9004-1c1c07c1986f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='frmPatrimony:tvSuporte:accPrincipal:behalfOf_4']</value>
      <webElementGuid>29e39004-1d59-44c3-b435-b3dad6fbe50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='frmPatrimony:tvSuporte:accPrincipal:behalfOf_items']/li[5]</value>
      <webElementGuid>25c3f088-4fc3-4111-b4bf-490167a276cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superficiário'])[4]/following::li[1]</value>
      <webElementGuid>b5e93b93-f2fc-47e9-aecd-61aac36d8017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usufrutuário'])[4]/following::li[2]</value>
      <webElementGuid>51049d63-4cd6-4809-afa8-c715bdf1c7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outro'])[2]/preceding::li[1]</value>
      <webElementGuid>73ed82f5-b942-46b2-8f57-cfa2476d13b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não preenchido'])[13]/preceding::li[2]</value>
      <webElementGuid>354fb20e-f1d1-4007-a8e1-8a3872acb583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/ul/li[5]</value>
      <webElementGuid>4bbf2f5b-8b49-4e3b-acdb-652c85765796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'frmPatrimony:tvSuporte:accPrincipal:behalfOf_4' and (text() = 'Técnico de Impostos' or . = 'Técnico de Impostos')]</value>
      <webElementGuid>364ea083-634c-49cd-904c-899b5d5e2ad9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
