<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>na_qualidade_de</name>
   <tag></tag>
   <elementGuidId>679cb73c-e984-4ff6-a6db-c51d449cd4dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='frmPatrimony:tvSuporte:accPrincipal:behalfOf_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>aa82a853-b45d-4609-a406-975bbfa46908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:behalfOf_label</value>
      <webElementGuid>30ddf19a-0852-4711-b913-5e76237786df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>eec49735-5766-4fd2-8d6e-82add1126fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Não preenchido</value>
      <webElementGuid>4f1e6217-7a93-4cdc-be3d-929ad9a7005f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:behalfOf_label&quot;)</value>
      <webElementGuid>2a2a1d2c-9a8c-42de-9354-733a95f74a19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='frmPatrimony:tvSuporte:accPrincipal:behalfOf_label']</value>
      <webElementGuid>9ef20800-12ca-481c-9b3c-c7280174ffb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPatrimony:tvSuporte:accPrincipal:behalfOf']/label</value>
      <webElementGuid>7c8c4321-706f-4c44-b82e-f37f21ff39cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Na Qualidade de*'])[1]/following::label[1]</value>
      <webElementGuid>511c302d-2243-4e7b-a7e5-d8c01a544343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome*'])[1]/following::label[2]</value>
      <webElementGuid>a8349606-9356-411c-83ef-8343e54f6120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDENTIFICAÇÃO DO IMÓVEL'])[1]/preceding::label[1]</value>
      <webElementGuid>661e6815-e7b6-4a28-b008-840ecae38bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome da Propriedade*'])[1]/preceding::label[1]</value>
      <webElementGuid>9b71cad6-ceb4-4066-b32f-805e4a3e5787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/label</value>
      <webElementGuid>2b5d1f73-3648-4e6f-b8df-6ee21e9133b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'frmPatrimony:tvSuporte:accPrincipal:behalfOf_label' and (text() = 'Não preenchido' or . = 'Não preenchido')]</value>
      <webElementGuid>1dcb07e6-adcd-44b1-a070-0e9dee8762e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
