<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nome_YURI do Contribuinte_frmSearchNIFBranchedialogSearchNIF-nameInput</name>
   <tag></tag>
   <elementGuidId>f17020f4-28a5-49da-8c22-030e94bb00a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmSearchNIFBranche:dialogSearchNIF-nameInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>197e1bd7-6862-410d-9019-275b7554b537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmSearchNIFBranche:dialogSearchNIF-nameInput</value>
      <webElementGuid>649ae914-ed39-4189-a1de-e8e49a3f3b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmSearchNIFBranche:dialogSearchNIF-nameInput</value>
      <webElementGuid>d6fa73ad-b3b3-43c7-b763-d8b2c46488a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>968f8b2d-f233-4395-aa20-e8157841ac95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all form-control ui-state-focus ui-state-hover</value>
      <webElementGuid>1b338c2b-bc8c-42b0-aeb5-bb919f2d03d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ec8f63fc-2aca-4f77-be24-314c8d6af0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f2691e16-0848-4869-9b97-097765ea656d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d9ad155-1854-46e6-a103-028377906a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSearchNIFBranche:dialogSearchNIF-nameInput&quot;)</value>
      <webElementGuid>15aef770-0333-4b04-8920-a7e160caefaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmSearchNIFBranche:dialogSearchNIF-nameInput']</value>
      <webElementGuid>82ba7d23-47ab-47c5-a639-a57ee0efb641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSearchNIFBranche']/div/div/input</value>
      <webElementGuid>d76bf868-a837-4a33-84d6-d5dcbeaba705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>de6b2499-04df-42c7-b704-1e628b4360ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmSearchNIFBranche:dialogSearchNIF-nameInput' and @name = 'frmSearchNIFBranche:dialogSearchNIF-nameInput' and @type = 'text']</value>
      <webElementGuid>8ddd52e2-997f-422b-8ee5-cb2d5f08300d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
