<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cadastro</name>
   <tag></tag>
   <elementGuidId>3487df34-1ef7-44e0-9770-45eae396bb76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='submenu13']/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.submenu.panel.servico-2 > a.collapsed > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b27f2384-8c3c-46da-ac85-89adc1adb89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cadastro</value>
      <webElementGuid>916c1a19-58ba-4766-afc8-543b1a881643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu13&quot;)/li[@class=&quot;submenu panel servico-2&quot;]/a[@class=&quot;collapsed&quot;]/span[1]</value>
      <webElementGuid>324a1f07-f3ed-4b19-b67d-9c6dc808769f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='submenu13']/li/a/span</value>
      <webElementGuid>ea2eb5e7-99eb-4b6a-81a3-aec7a4fed61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Património'])[2]/following::span[1]</value>
      <webElementGuid>35768c44-5d8d-4071-b56d-065d2681c644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultar'])[2]/following::span[2]</value>
      <webElementGuid>bb068b3b-12ff-4f26-ae48-60a46f1812a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesquisar'])[1]/preceding::span[1]</value>
      <webElementGuid>4dc987e8-4e1c-4025-895b-020030470d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prédio'])[1]/preceding::span[2]</value>
      <webElementGuid>36879714-30c4-4981-9a5f-01d4cca0b0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cadastro']/parent::*</value>
      <webElementGuid>8b006263-7b61-4565-b6cb-9bacfb8b4fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/ul/li[3]/ul/li/a/span</value>
      <webElementGuid>c3190fd9-a6f9-4369-b743-65c9ec9c28e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cadastro' or . = 'Cadastro')]</value>
      <webElementGuid>1e37da13-ce9d-446c-bbce-4da06fb57849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
