<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pesquisar</name>
   <tag></tag>
   <elementGuidId>e3520cf0-c7f7-4523-a0f2-709f3afbb4cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmSearchNIFBranche:btnSearchTaxpayerBranch']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>104dac62-9f89-4a04-a9c9-0b83ad9ec0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>ceed258f-db39-4764-80ba-c07d8124ff79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesquisar</value>
      <webElementGuid>721be19c-3872-425e-be38-4b5c43088451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSearchNIFBranche:btnSearchTaxpayerBranch&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>e319a8b7-8a99-4387-9db4-0cdf04ad9fcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='frmSearchNIFBranche:btnSearchTaxpayerBranch']/span</value>
      <webElementGuid>1c804c3d-a391-4d06-aade-bddd0c237be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passaporte'])[2]/following::span[1]</value>
      <webElementGuid>dc46f576-805f-460a-9b16-02321fb75bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nº de Registo Comercial'])[2]/following::span[1]</value>
      <webElementGuid>4ca50c6b-cfce-42c4-905b-1e27e345e1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de ID'])[1]/preceding::span[1]</value>
      <webElementGuid>0d34b432-691b-46e8-990f-06cc4a99e3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[4]/preceding::span[2]</value>
      <webElementGuid>28539985-89bd-41ff-804c-ff0f751c7a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button/span</value>
      <webElementGuid>4db1387a-9b07-438b-9314-0270d6985e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pesquisar' or . = 'Pesquisar')]</value>
      <webElementGuid>3aa772c1-1076-4b78-b911-97b169d52b35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
