<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ui-button_1</name>
   <tag></tag>
   <elementGuidId>90ecf9ac-8467-48cc-8dfc-d815da487100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-button-text.ui-c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmPatrimony:tvSuporte:accPrincipal:btnSerchPerson1']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6e79ce9-a4b7-4297-9517-c21f7fe15893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>b502fa3c-4510-4037-b799-0ce043398d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ui-button</value>
      <webElementGuid>7d963042-abcb-44c0-8f95-38ed2c10f127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:btnSerchPerson1&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>25837f24-cbd5-4315-b461-8a766696c8b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='frmPatrimony:tvSuporte:accPrincipal:btnSerchPerson1']/span[2]</value>
      <webElementGuid>60aba509-77ae-4430-8cc9-910f309b79e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIF*'])[1]/following::span[2]</value>
      <webElementGuid>b35e06b3-75c1-42f7-9b2d-4fd8cd555066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDENTIFICAÇÃO DO DECLARANTE'])[1]/following::span[3]</value>
      <webElementGuid>56c9e5d1-ac76-4c4c-a71b-31ab15185ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[2]/preceding::span[2]</value>
      <webElementGuid>56e777c0-8174-4c8c-835c-511df173f1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nome*'])[1]/preceding::span[3]</value>
      <webElementGuid>d4e59e82-8fa8-423e-9118-a6b1f46f897e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ui-button']/parent::*</value>
      <webElementGuid>5967a3a2-32d6-4886-bd1c-11bf356afdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span[2]</value>
      <webElementGuid>179eb673-5716-4fbe-af81-5baaca0b300d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ui-button' or . = 'ui-button')]</value>
      <webElementGuid>264b8cf6-bc09-4540-bf06-33d8eb340988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
