<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tipo_direito</name>
   <tag></tag>
   <elementGuidId>87dbd7ac-11d7-463e-b06d-1382d9d1f1f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='formRegisterOwnerModal:patrimonyOwnerType_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9d252d0c-6d43-47d2-b353-572be89dae5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formRegisterOwnerModal:patrimonyOwnerType_label</value>
      <webElementGuid>93723d59-904f-4d68-ba42-e6d6cbb7b004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>abba1539-08b9-4e60-b3e9-ea8341d8aad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Não preenchido</value>
      <webElementGuid>22bf7e51-6ee3-434a-aa24-d88ad968e993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegisterOwnerModal:patrimonyOwnerType_label&quot;)</value>
      <webElementGuid>d3537bc7-178f-4e2f-9ed1-92c4451441f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='formRegisterOwnerModal:patrimonyOwnerType_label']</value>
      <webElementGuid>3ed210fd-fb72-4b42-8058-4f7cbc39f9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formRegisterOwnerModal:patrimonyOwnerType']/label</value>
      <webElementGuid>3423c67a-42f6-4679-a9cf-c610839690f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Direito*'])[1]/following::label[1]</value>
      <webElementGuid>f23e6793-cc59-420b-9bfd-cac44ce75a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsável'])[2]/following::label[2]</value>
      <webElementGuid>b2fb12c2-95ef-4e9b-ad86-b17440f72468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não preenchido'])[11]/preceding::label[1]</value>
      <webElementGuid>c7a547a0-e3aa-4d6f-8d3a-22bc1788bc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proprietário'])[3]/preceding::label[1]</value>
      <webElementGuid>575e831b-ab8c-4ac8-8f97-13b0c8d57ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[4]/div/div/label</value>
      <webElementGuid>d866e94e-90c0-492d-8ef0-c567eb3e62fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'formRegisterOwnerModal:patrimonyOwnerType_label' and (text() = 'Não preenchido' or . = 'Não preenchido')]</value>
      <webElementGuid>298cdc7b-3f64-47ff-9243-a6f1ac041c13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
