<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titular_Proprietrio</name>
   <tag></tag>
   <elementGuidId>09bc1b38-f119-4dd2-97c7-5a2222f04887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='formRegisterOwnerModal:patrimonyOwnerType_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e194f665-96d7-415e-8a15-0241efcb1da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>dba6758f-b54a-43c9-af45-b98a8db5675b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Proprietário</value>
      <webElementGuid>21104276-9efe-4d7d-9ee0-529368182376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4b65e40e-f68b-42fe-9d94-06e07501f759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cce61e10-a25e-45d9-93aa-9047019e1a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formRegisterOwnerModal:patrimonyOwnerType_1</value>
      <webElementGuid>58be00a0-75ec-43d3-bdff-f48957984ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proprietário</value>
      <webElementGuid>87fb2822-60cb-4f9b-98d6-ae3ef28c92bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegisterOwnerModal:patrimonyOwnerType_1&quot;)</value>
      <webElementGuid>55b1bc50-9bf3-4a93-9b5b-edfbd775eb6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='formRegisterOwnerModal:patrimonyOwnerType_1']</value>
      <webElementGuid>49238400-fc74-4514-b8f2-f089786657d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='formRegisterOwnerModal:patrimonyOwnerType_items']/li[2]</value>
      <webElementGuid>fec7f3b3-fe81-4bc1-93cd-c83f8d1990b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não preenchido'])[11]/following::li[1]</value>
      <webElementGuid>3b757cbc-a723-4581-b826-b8f93c2530c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não preenchido'])[10]/following::li[2]</value>
      <webElementGuid>2eaf0f2d-016f-4a30-ada8-2a8eaadffe99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usufrutuário'])[3]/preceding::li[1]</value>
      <webElementGuid>baeb2b94-1f4e-4f99-a45d-9895ee37c570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superficiário'])[3]/preceding::li[2]</value>
      <webElementGuid>11c3abd7-6f31-483d-9697-c266c8b7b595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[4]/div/div/div[4]/div/ul/li[2]</value>
      <webElementGuid>cb25d57b-e97f-419f-b113-34effb5e9767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'formRegisterOwnerModal:patrimonyOwnerType_1' and (text() = 'Proprietário' or . = 'Proprietário')]</value>
      <webElementGuid>96057711-2ade-40e1-b229-123e330046ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
