<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Valor Declarado (Kz)_frmPatrimonytvSuporteaccPrincipaldeclaredValue_input</name>
   <tag></tag>
   <elementGuidId>0d5fe83f-7267-4072-9d98-f60ac978640d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fad9a5b-a8cc-4abc-a074-9797200464fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:declaredValue_input</value>
      <webElementGuid>346f5e96-148e-4303-b7a4-f6476b410fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPatrimony:tvSuporte:accPrincipal:declaredValue_input</value>
      <webElementGuid>89e309ef-d90a-4454-8b6d-282195fec49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea188c09-6776-4702-9fc8-4e2675880c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a713eea0-6eec-49d3-8627-a13c4d04228f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;frmPatrimony:tvSuporte:accPrincipal:declaredValue&quot;,e:&quot;valueChange&quot;,p:&quot;frmPatrimony&quot;,u:&quot;frmPatrimony&quot;});</value>
      <webElementGuid>c5cffde5-c311-46de-b7d8-0a9ab64a19de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>476a0e1e-c28a-48e3-9119-1db8239a0072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-con</name>
      <type>Main</type>
      <value>javax.faces.BigDecimal</value>
      <webElementGuid>136b21a7-5211-466c-b6a3-e906d4f55c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-hl</name>
      <type>Main</type>
      <value>inputnumber</value>
      <webElementGuid>d88563b6-34d6-4fb3-9195-7d2729a3e269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b835c297-56a8-4f86-85b6-f03adb7610c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>282dc1c4-157d-4630-935c-41cc835b7bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>70a1fadc-b286-427d-a35b-0371d3ab7ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPatrimony:tvSuporte:accPrincipal:declaredValue_input&quot;)</value>
      <webElementGuid>505cf363-1713-49db-980d-3e924bf3f304</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue_input']</value>
      <webElementGuid>da0570da-37a8-4243-84f7-e4dc70095907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='frmPatrimony:tvSuporte:accPrincipal:declaredValue']/input</value>
      <webElementGuid>e5e97441-d1be-4d07-b99b-cb3f7de7e40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[8]/div/span/input</value>
      <webElementGuid>1c751cd7-8ed3-44de-9ab5-e813f879c194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPatrimony:tvSuporte:accPrincipal:declaredValue_input' and @name = 'frmPatrimony:tvSuporte:accPrincipal:declaredValue_input' and @type = 'text']</value>
      <webElementGuid>715e107e-dc54-443b-9aca-dff63824bf39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
