<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ASSINATURAS</name>
   <tag></tag>
   <elementGuidId>a3fc3132-a5df-4633-9f25-ff6f513f889e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.d-none.d-lg-block.nav-link.classificados</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo-menu-container']/nav/div/div/div/a[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79459dd5-0858-48ea-aa92-f1d65f4d697c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-lg-block nav-link classificados</value>
      <webElementGuid>86b59efb-0122-4757-b2e3-5337a674d10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/utentes/subscricoes.php?go</value>
      <webElementGuid>cc36c60c-6e97-4921-9222-9fcc5cd0c0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ASSINATURAS</value>
      <webElementGuid>4510afe8-22f5-4cf5-8503-809ada09452d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-menu-container&quot;)/nav[@class=&quot;nav&quot;]/div[@class=&quot;container position-relative&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xl-10 flex-wrap d-flex justify-content-end justify-content-lg-center justify-content-xl-between main-menu-container&quot;]/a[@class=&quot;d-none d-lg-block nav-link classificados&quot;]</value>
      <webElementGuid>0a7a8573-c4fb-4bf2-93fb-dcadaddb45fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo-menu-container']/nav/div/div/div/a[11]</value>
      <webElementGuid>3eb81a16-92c6-48f0-9891-e1bcba01fe43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ASSINATURAS')]</value>
      <webElementGuid>5956ce7c-c78e-46b1-81a5-9abad8a5d990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUNDO'])[1]/following::a[1]</value>
      <webElementGuid>3edfcc5a-260a-4cbf-a1e6-9ff38daf425c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPINIÃO'])[1]/following::a[2]</value>
      <webElementGuid>c6416848-0089-43d7-a299-6c00ee84079b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Política'])[2]/preceding::a[6]</value>
      <webElementGuid>780cdefa-6d2c-4d34-b690-49b35f809804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ASSINATURAS']/parent::*</value>
      <webElementGuid>18420827-219a-408f-b0be-77e55ccbe364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/utentes/subscricoes.php?go')])[2]</value>
      <webElementGuid>0d9619b0-3a43-4c50-b23b-6b8b228596a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[11]</value>
      <webElementGuid>5da2b85c-171a-425d-8c3a-2ef30a39b366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/utentes/subscricoes.php?go' and (text() = 'ASSINATURAS' or . = 'ASSINATURAS')]</value>
      <webElementGuid>d0f736c7-029f-4e0a-a3f7-ab8814777416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
