<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CULTURA</name>
   <tag></tag>
   <elementGuidId>9783c9c9-4953-49bb-8dc6-e5412d5c937a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo-menu-container']/nav/div/div/div/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5d5a981-8402-4864-8043-50812d2befb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-lg-block nav-link </value>
      <webElementGuid>4cc1ce43-5bc9-47e1-8ad5-59d89dae5478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ao/noticias/index.php?tipo=1&amp;idSec=17</value>
      <webElementGuid>67048424-c576-4980-8384-ae8b04763210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CULTURA</value>
      <webElementGuid>19e92e6a-6ae7-4992-9591-849abfbd575e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-menu-container&quot;)/nav[@class=&quot;nav&quot;]/div[@class=&quot;container position-relative&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xl-10 flex-wrap d-flex justify-content-end justify-content-lg-center justify-content-xl-between main-menu-container&quot;]/a[@class=&quot;d-none d-lg-block nav-link&quot;]</value>
      <webElementGuid>9426ed89-f6b6-4e4a-aeb4-b34821c89cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo-menu-container']/nav/div/div/div/a[5]</value>
      <webElementGuid>61215579-5252-472c-bc7b-816fe3772dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CULTURA')]</value>
      <webElementGuid>f1130501-8bba-4f91-ad05-4e5753db7e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ECONOMIA'])[1]/following::a[1]</value>
      <webElementGuid>07b0b4d3-dbb6-4c3b-8aaa-e9812ddc01e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOCIEDADE'])[1]/following::a[2]</value>
      <webElementGuid>271a2ce0-58b7-4111-a39c-e10fb1468fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESPORTO'])[1]/preceding::a[1]</value>
      <webElementGuid>61965b09-0dea-458f-955f-39e5aa029f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENTREVISTA'])[1]/preceding::a[2]</value>
      <webElementGuid>0edf6d76-740c-4809-b750-d76dc3ff4761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CULTURA']/parent::*</value>
      <webElementGuid>fcd5ae06-2cc8-4b55-bff4-092f2c117c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ao/noticias/index.php?tipo=1&amp;idSec=17')]</value>
      <webElementGuid>23f6d7df-57aa-4803-af1b-bd3f1b761d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>c8b92839-f010-4432-889e-44389360a9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ao/noticias/index.php?tipo=1&amp;idSec=17' and (text() = 'CULTURA' or . = 'CULTURA')]</value>
      <webElementGuid>82c161f8-1fff-46f1-b09f-2db26b0fe89c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
