<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DESPORTO</name>
   <tag></tag>
   <elementGuidId>1f56f11d-71f6-4162-b844-36a08676cbb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo-menu-container']/nav/div/div/div/a[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a885513b-3b91-465e-b5c9-03f342e5db90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-lg-block nav-link </value>
      <webElementGuid>ca660743-66eb-45e7-9f4d-71289c5fc902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ao/noticias/index.php?tipo=1&amp;idSec=16</value>
      <webElementGuid>4a24ec9e-f215-4081-9fd8-7c30c2bbe36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DESPORTO</value>
      <webElementGuid>d518723f-2d86-4fd1-be32-bb689ed4e150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-menu-container&quot;)/nav[@class=&quot;nav&quot;]/div[@class=&quot;container position-relative&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xl-10 flex-wrap d-flex justify-content-end justify-content-lg-center justify-content-xl-between main-menu-container&quot;]/a[@class=&quot;d-none d-lg-block nav-link&quot;]</value>
      <webElementGuid>08156c4a-5779-413d-914a-311430e08665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo-menu-container']/nav/div/div/div/a[6]</value>
      <webElementGuid>e714fe15-dbcb-4a20-8395-806912e998df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DESPORTO')]</value>
      <webElementGuid>fa178014-632c-4aa8-a0b8-1e08cefed3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CULTURA'])[1]/following::a[1]</value>
      <webElementGuid>1043eaa1-4641-411e-8d3b-6bf0d4067c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ECONOMIA'])[1]/following::a[2]</value>
      <webElementGuid>e369ef44-c020-46bd-ac51-a45f08cbe76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENTREVISTA'])[1]/preceding::a[1]</value>
      <webElementGuid>94644664-b531-4cad-a90e-7cbb0a2336e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPORTAGEM'])[1]/preceding::a[2]</value>
      <webElementGuid>77a2c751-dd66-421e-a030-96b6682f5ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DESPORTO']/parent::*</value>
      <webElementGuid>ec124ead-d72f-44a4-9f25-65d1ae92b9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ao/noticias/index.php?tipo=1&amp;idSec=16')]</value>
      <webElementGuid>5e932e6e-9ad2-4fa2-9206-d90ecd78b87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>fe747b80-b876-4e9f-af79-be53a8a76f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ao/noticias/index.php?tipo=1&amp;idSec=16' and (text() = 'DESPORTO' or . = 'DESPORTO')]</value>
      <webElementGuid>e87c5552-8a35-499e-9661-bc9539e375b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
