<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MUNDO</name>
   <tag></tag>
   <elementGuidId>79269ca2-e147-4489-83cb-f584d0cd6fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo-menu-container']/nav/div/div/div/a[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e71df0cf-fe2d-43b2-baec-104e7c230852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-lg-block nav-link </value>
      <webElementGuid>da35cf5e-44c1-42f7-8dbb-caecbe6af1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://jornaldeangola.ao/ao/noticias/index.php?tipo=1&amp;idSec=13</value>
      <webElementGuid>90e7c823-b19a-4762-ad46-d52a069afd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MUNDO</value>
      <webElementGuid>38b7ea57-d207-4466-ab4c-49e407da0330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-menu-container&quot;)/nav[@class=&quot;nav&quot;]/div[@class=&quot;container position-relative&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xl-10 flex-wrap d-flex justify-content-end justify-content-lg-center justify-content-xl-between main-menu-container&quot;]/a[@class=&quot;d-none d-lg-block nav-link&quot;]</value>
      <webElementGuid>cebd0423-65fe-4375-9751-fd6666c2521a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo-menu-container']/nav/div/div/div/a[10]</value>
      <webElementGuid>6ed03485-27a2-4e8b-9cc5-d9199611e3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MUNDO')]</value>
      <webElementGuid>f730293b-76fd-48cf-b8cb-3a7a04eac4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPINIÃO'])[1]/following::a[1]</value>
      <webElementGuid>7020230c-8c25-4f0e-8890-554d283202f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPORTAGEM'])[1]/following::a[2]</value>
      <webElementGuid>1f4d7eaf-d6b1-47fe-a54f-2f39913ab175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASSINATURAS'])[1]/preceding::a[1]</value>
      <webElementGuid>a8428c38-bd72-4a7a-b4d8-0957fd52db58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Política'])[2]/preceding::a[7]</value>
      <webElementGuid>d927909b-737c-45b5-b456-2010518f0e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MUNDO']/parent::*</value>
      <webElementGuid>f3f83d05-f00f-413a-8f2e-bc55cf67b71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://jornaldeangola.ao/ao/noticias/index.php?tipo=1&amp;idSec=13')]</value>
      <webElementGuid>4598a9f9-30ae-4118-a800-ab3d8bbdb279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[10]</value>
      <webElementGuid>d9317c22-b3fa-4eb5-af63-640a33057238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://jornaldeangola.ao/ao/noticias/index.php?tipo=1&amp;idSec=13' and (text() = 'MUNDO' or . = 'MUNDO')]</value>
      <webElementGuid>e2c05f47-d120-4f94-b275-02d38ff26d0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
