<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_REPORTAGEM</name>
   <tag></tag>
   <elementGuidId>f1d7ca3c-c438-44a5-b3ac-a69e2a3946b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo-menu-container']/nav/div/div/div/a[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8278171-2c53-49c1-9766-cd1896d29c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-lg-block nav-link </value>
      <webElementGuid>9589fd37-2130-4774-98dc-12f03d4066c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ao/noticias/index.php?tipo=1&amp;idSec=25</value>
      <webElementGuid>fbb94418-91ca-47b4-9985-a9aaf1b26e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REPORTAGEM</value>
      <webElementGuid>006075a5-2e44-4982-b9ef-eb16f3061273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-menu-container&quot;)/nav[@class=&quot;nav&quot;]/div[@class=&quot;container position-relative&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xl-10 flex-wrap d-flex justify-content-end justify-content-lg-center justify-content-xl-between main-menu-container&quot;]/a[@class=&quot;d-none d-lg-block nav-link&quot;]</value>
      <webElementGuid>1b74f874-bc4b-4dab-b638-aa2bb4226154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logo-menu-container']/nav/div/div/div/a[8]</value>
      <webElementGuid>f735a696-3492-4a72-8985-ea9ea7bc2b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'REPORTAGEM')]</value>
      <webElementGuid>80db6c13-1313-45e9-a78d-d881dd3bd411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENTREVISTA'])[1]/following::a[1]</value>
      <webElementGuid>2a5f7c68-2bc2-491e-9bc3-3f364a667f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESPORTO'])[1]/following::a[2]</value>
      <webElementGuid>653208ef-5a83-4c21-90a0-017c49ea4177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OPINIÃO'])[1]/preceding::a[1]</value>
      <webElementGuid>604f69d1-72f8-4b07-9054-fb58924be402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUNDO'])[1]/preceding::a[2]</value>
      <webElementGuid>a30f6d07-1e9f-42fe-b3d5-b6b2bc92183c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REPORTAGEM']/parent::*</value>
      <webElementGuid>e6532a43-5a58-4c4e-b655-54e7d189f380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ao/noticias/index.php?tipo=1&amp;idSec=25')]</value>
      <webElementGuid>ef027ba1-b230-4071-9cfe-5bd52c18ee2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[8]</value>
      <webElementGuid>7f8c91a7-cd2d-40ad-b14f-afc41deee719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ao/noticias/index.php?tipo=1&amp;idSec=25' and (text() = 'REPORTAGEM' or . = 'REPORTAGEM')]</value>
      <webElementGuid>7079ffc5-e39e-425d-8a44-fe645a36148d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
