<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Imagens</name>
   <tag></tag>
   <elementGuidId>71ea3759-290c-487f-83ef-2928269cabef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-msb']/div/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ca8d3a12-fc23-4024-9d19-d1e275f808ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=National+Geographic+Brasil&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwiX66OQk7f-AhVNTsAKHW7ECwMQ_AUoAnoECAEQBA</value>
      <webElementGuid>2bb676be-831b-48fa-96e3-49f7c93539fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hveid</name>
      <type>Main</type>
      <value>CAEQBA</value>
      <webElementGuid>9cf37d22-4f7f-4c49-b5dd-501c13ce0c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imagens</value>
      <webElementGuid>7f463100-ad31-4a36-b7c2-e62125af4869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-msb&quot;)/div[1]/div[@class=&quot;MUFPAc&quot;]/div[@class=&quot;hdtb-mitem&quot;]/a[1]</value>
      <webElementGuid>6a5be2f0-848c-4184-bd33-d065ce10104d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-msb']/div/div/div[3]/a</value>
      <webElementGuid>8b2a1cea-0c90-487e-b566-45c932fe02cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Imagens')]</value>
      <webElementGuid>6bf803f6-d339-4d00-b0fa-87f76333f88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vídeos'])[1]/following::a[1]</value>
      <webElementGuid>ae3c78b9-ab37-493c-a39c-fd1a56f11b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tudo'])[1]/following::a[2]</value>
      <webElementGuid>a09d94f7-9f8d-44e2-81dd-e73ac1a9fd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notícias'])[1]/preceding::a[1]</value>
      <webElementGuid>98eddf84-875a-48aa-9e6f-64de8b6694d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maps'])[1]/preceding::a[2]</value>
      <webElementGuid>c49f7121-aef2-4b1e-a83a-4769932385b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Imagens']/parent::*</value>
      <webElementGuid>d4940bfa-2b4b-47e7-802f-a81a4d48136c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?q=National+Geographic+Brasil&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwiX66OQk7f-AhVNTsAKHW7ECwMQ_AUoAnoECAEQBA')]</value>
      <webElementGuid>1f92b582-5d62-4a85-8b22-6a37e0ea5dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/a</value>
      <webElementGuid>afec510c-3720-40d9-a654-3594b7fe0a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=National+Geographic+Brasil&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;source=lnms&amp;tbm=isch&amp;sa=X&amp;ved=2ahUKEwiX66OQk7f-AhVNTsAKHW7ECwMQ_AUoAnoECAEQBA' and (text() = 'Imagens' or . = 'Imagens')]</value>
      <webElementGuid>27cba1cc-c53e-4822-8581-1b704936e509</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
