<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Notcias</name>
   <tag></tag>
   <elementGuidId>94b40e2b-e9e4-4edd-964e-6869e6774585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-msb']/div/div/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83d3c2ed-e346-47bc-a657-2ec722109553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=National+Geographic+Brasil&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;source=lnms&amp;tbm=nws&amp;sa=X&amp;ved=2ahUKEwiX66OQk7f-AhVNTsAKHW7ECwMQ_AUoA3oECAEQBQ</value>
      <webElementGuid>e031309e-98e3-4828-8b54-9fede90c590b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hveid</name>
      <type>Main</type>
      <value>CAEQBQ</value>
      <webElementGuid>f877e0ff-5c38-403e-a199-38e30e92f718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Notícias</value>
      <webElementGuid>edf49b9c-c811-45ca-aa65-ce1be98adcfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-msb&quot;)/div[1]/div[@class=&quot;MUFPAc&quot;]/div[@class=&quot;hdtb-mitem&quot;]/a[1]</value>
      <webElementGuid>76c4a8e7-6eff-4710-8467-cef677c1854d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-msb']/div/div/div[4]/a</value>
      <webElementGuid>6ca45a42-b9a3-43b9-a291-696773c34d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Notícias')]</value>
      <webElementGuid>c2aa6f74-342f-45bf-88d8-23265adb200d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imagens'])[1]/following::a[1]</value>
      <webElementGuid>349191c2-ccdd-4053-a8d8-937c83e731c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vídeos'])[1]/following::a[2]</value>
      <webElementGuid>cf15c994-6008-4327-90ea-645f61f86041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maps'])[1]/preceding::a[1]</value>
      <webElementGuid>e98d512e-3983-4dab-85d8-0b3893e3da4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mais'])[1]/preceding::a[2]</value>
      <webElementGuid>cdf78efc-b199-4221-b541-e25669194350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Notícias']/parent::*</value>
      <webElementGuid>cd1eab7f-acfd-4465-bf29-3fd03fa6f97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search?q=National+Geographic+Brasil&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;source=lnms&amp;tbm=nws&amp;sa=X&amp;ved=2ahUKEwiX66OQk7f-AhVNTsAKHW7ECwMQ_AUoA3oECAEQBQ')]</value>
      <webElementGuid>a4c8e205-13c5-43a3-9ebd-6900dbb2d60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>0893d212-9c7c-49bb-b5e8-97f24924f0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=National+Geographic+Brasil&amp;rlz=1C1GCEU_pt-PTAO1024AO1024&amp;source=lnms&amp;tbm=nws&amp;sa=X&amp;ved=2ahUKEwiX66OQk7f-AhVNTsAKHW7ECwMQ_AUoA3oECAEQBQ' and (text() = 'Notícias' or . = 'Notícias')]</value>
      <webElementGuid>1d891207-cc9b-4088-9fd8-485a96884aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
