<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_O que significa natgeo_L3Ezfd</name>
   <tag></tag>
   <elementGuidId>3fdfb3ae-fd67-49df-84dd-32e4aedd6422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zHlAZLvgCMmdgQa6852QCg__25']/div/div/div[2]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#zHlAZLvgCMmdgQa6852QCg__25 > div.wQiwMc.related-question-pair > div.HYvwY.ilulF.roMIYb.oST1qe.g7pt6d.h373nd > div:nth-of-type(2) > div.dnXCYb > div.L3Ezfd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57458b68-ae8c-48fb-bb2a-26acc4924661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>pcRaIe</value>
      <webElementGuid>e185246f-900c-417f-a0c7-aeda51cc627d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>L3Ezfd</value>
      <webElementGuid>13025fa2-64cd-41fb-9e86-94e8d28a7110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwi79uyTjbf-AhXJTsAKHbp5B6IQuk56BAgSEAI</value>
      <webElementGuid>705352d6-9113-4d5e-b894-2c25f5a7de24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zHlAZLvgCMmdgQa6852QCg__25&quot;)/div[@class=&quot;wQiwMc related-question-pair&quot;]/div[@class=&quot;HYvwY ilulF roMIYb oST1qe g7pt6d h373nd&quot;]/div[2]/div[@class=&quot;dnXCYb&quot;]/div[@class=&quot;L3Ezfd&quot;]</value>
      <webElementGuid>8a6331bb-879b-40d8-9d87-bd4bf295c1e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zHlAZLvgCMmdgQa6852QCg__25']/div/div/div[2]/div/div[3]</value>
      <webElementGuid>bcfa7130-d1a5-416a-a08c-e406b597cbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div[3]</value>
      <webElementGuid>7fa3cbc4-5622-4d6a-b1b2-d0b24b3f10a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
