<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tem National Geographic na Netflix_L3Ezfd</name>
   <tag></tag>
   <elementGuidId>c2704cf9-8074-41bb-af94-2ebb4cb7600b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='6XlAZNnHLM6ChbIPku-MsAo__2']/div/div/div[2]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6XlAZNnHLM6ChbIPku-MsAo__2 > div.wQiwMc.related-question-pair > div.HYvwY.ilulF.roMIYb.oST1qe.g7pt6d.h373nd > div:nth-of-type(2) > div.dnXCYb > div.L3Ezfd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfcd537e-504d-49a1-9d95-357339353435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>pcRaIe</value>
      <webElementGuid>b7756125-c976-48b8-b335-84031069dda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>L3Ezfd</value>
      <webElementGuid>81555235-d6b6-426c-8f25-119332f30e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwiZ4Pqhjbf-AhVOQUEAHZI3A6YQuk56BAgCEAI</value>
      <webElementGuid>019c2bc9-b7a7-4869-b1f5-90c1164cf684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6XlAZNnHLM6ChbIPku-MsAo__2&quot;)/div[@class=&quot;wQiwMc related-question-pair&quot;]/div[@class=&quot;HYvwY ilulF roMIYb oST1qe g7pt6d h373nd&quot;]/div[2]/div[@class=&quot;dnXCYb&quot;]/div[@class=&quot;L3Ezfd&quot;]</value>
      <webElementGuid>bfb6bba8-4b66-444c-be7a-859309a1e6f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='6XlAZNnHLM6ChbIPku-MsAo__2']/div/div/div[2]/div/div[3]</value>
      <webElementGuid>2cc4ef7d-91ed-4c24-8501-f25bf47c6293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div[3]</value>
      <webElementGuid>e58dbcac-1fca-4d36-8f50-bafb3d69aff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
