<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Ajuda</name>
   <tag></tag>
   <elementGuidId>83f407f2-e6c8-43f4-878d-99cc6a3a4eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/h2[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>cf941225-2815-4013-b79f-aefe6bca12ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Ajuda</value>
      <webElementGuid>0f7e55b3-8411-40ed-a93e-ba1b9b1b491e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1</value>
      <webElementGuid>937ce930-765f-4a25-af35-5b3b86f6c136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>header_top_nav</value>
      <webElementGuid>1748ed86-a9fb-4561-b635-d9344194f48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-info</name>
      <type>Main</type>
      <value>{&quot;component_name&quot;:&quot;header_top_nav&quot;,&quot;component_type&quot;:&quot;links&quot;,&quot;nav_location&quot;:&quot;header&quot;,&quot;nav_item&quot;:&quot;top_level_click&quot;,&quot;nav_text&quot;:&quot;ajuda&quot;,&quot;current_page_url&quot;:&quot;https://www.dstv.com/pt-ao&quot;,&quot;target_page_url&quot;:&quot;/pt-ao/&quot;}</value>
      <webElementGuid>fa382166-00f3-434c-b66d-20a5b5d95fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajuda</value>
      <webElementGuid>96f1ef20-5cea-4519-9cc2-5718586d0cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-menu-top-dark text-white position-sticky&quot;]/div[@class=&quot;container-fluid container-xl container-md&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[@class=&quot;d-flex flex-row align-items-center&quot;]/div[@class=&quot;active-site-nav d-flex flex-row list-fill-animation-7&quot;]/h2[@class=&quot;mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1&quot;]</value>
      <webElementGuid>593aee62-e8be-47b6-b161-c144f7889bd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/h2[6]</value>
      <webElementGuid>6a8a1463-7242-4786-9418-33421d64c8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyDStv'])[1]/following::h2[1]</value>
      <webElementGuid>9b4c8ea4-07bd-4731-926c-33dba6054d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagamento'])[1]/following::h2[2]</value>
      <webElementGuid>25ce86b8-a3f7-4db9-b7c9-472d21dad553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sobre'])[1]/preceding::h2[1]</value>
      <webElementGuid>fde7f7e1-1d5d-4003-b2b7-971f6c9ac4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajuda']/parent::*</value>
      <webElementGuid>9f06f418-ac75-40c3-aa9f-5a46c43a21e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[6]</value>
      <webElementGuid>0996807c-ac2b-4479-a882-0aebf6dbb012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Ajuda' or . = 'Ajuda')]</value>
      <webElementGuid>35170e5b-b358-40a7-8209-946d89a245a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
