<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Adira</name>
   <tag></tag>
   <elementGuidId>0196ba07-1b90-4682-9780-1d2ab6953c97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/h2[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>2aea7ae1-949f-4af2-955e-4ad572d3cbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Adira</value>
      <webElementGuid>fb974dfd-1685-448c-8366-aa4333a62f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1</value>
      <webElementGuid>b1744565-27c2-4e1d-bc05-d2e6319e66f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>header_top_nav</value>
      <webElementGuid>08e4f0f9-a540-47b4-8a08-82ac56d8e517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-info</name>
      <type>Main</type>
      <value>{&quot;component_name&quot;:&quot;header_top_nav&quot;,&quot;component_type&quot;:&quot;links&quot;,&quot;nav_location&quot;:&quot;header&quot;,&quot;nav_item&quot;:&quot;top_level_click&quot;,&quot;nav_text&quot;:&quot;adira&quot;,&quot;current_page_url&quot;:&quot;https://www.dstv.com/pt-ao&quot;,&quot;target_page_url&quot;:&quot;/pt-ao/&quot;}</value>
      <webElementGuid>3c07dccb-bc99-4439-8c7c-60219c967c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adira</value>
      <webElementGuid>4ba85549-1b85-41cd-a994-2dba27616d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-menu-top-dark text-white position-sticky&quot;]/div[@class=&quot;container-fluid container-xl container-md&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[@class=&quot;d-flex flex-row align-items-center&quot;]/div[@class=&quot;active-site-nav d-flex flex-row list-fill-animation-7&quot;]/h2[@class=&quot;mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1&quot;]</value>
      <webElementGuid>12a38d38-4782-4d87-9212-402f8530dbd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/h2[3]</value>
      <webElementGuid>95e35100-0254-4fb3-985d-c5c871181705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descobrir'])[1]/following::h2[1]</value>
      <webElementGuid>37c9b1f2-d3e3-4065-8ee0-d7e0f058b1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programação'])[1]/following::h2[2]</value>
      <webElementGuid>030c11e5-6159-4990-b2a7-b93ec2b134da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagamento'])[1]/preceding::h2[1]</value>
      <webElementGuid>3ea872c6-41b9-40cd-96dd-82fd7cc23a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyDStv'])[1]/preceding::h2[2]</value>
      <webElementGuid>c3599f6b-f8e5-4d12-852f-3de7c7ac5c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adira']/parent::*</value>
      <webElementGuid>87caf337-cdb9-483b-9539-b1691cd1489e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[3]</value>
      <webElementGuid>698f3c72-6f1e-43fb-944e-cb9693d17dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Adira' or . = 'Adira')]</value>
      <webElementGuid>62b5d3b7-c217-4499-9c56-edbd541716ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
