<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Descobrir</name>
   <tag></tag>
   <elementGuidId>befcb2d0-8b9c-4ed6-b81f-229030de9f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/h2[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>36c08395-4356-4b97-9194-c0b8d9159663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Descobrir</value>
      <webElementGuid>a0d1f233-e877-48eb-8885-2bc2f9f9b9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1</value>
      <webElementGuid>7dd14018-868e-4d7c-874a-e751ffe023c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>header_top_nav</value>
      <webElementGuid>f211a0f8-ddb4-48b2-abb3-c4fabdd058e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-info</name>
      <type>Main</type>
      <value>{&quot;component_name&quot;:&quot;header_top_nav&quot;,&quot;component_type&quot;:&quot;links&quot;,&quot;nav_location&quot;:&quot;header&quot;,&quot;nav_item&quot;:&quot;top_level_click&quot;,&quot;nav_text&quot;:&quot;descobrir&quot;,&quot;current_page_url&quot;:&quot;https://www.dstv.com/pt-ao&quot;,&quot;target_page_url&quot;:&quot;/pt-ao/&quot;}</value>
      <webElementGuid>a38cf827-e26f-44dc-81bf-fa60d81dccbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descobrir</value>
      <webElementGuid>803760fb-2f6d-4deb-8eeb-11645d45783a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-menu-top-dark text-white position-sticky&quot;]/div[@class=&quot;container-fluid container-xl container-md&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[@class=&quot;d-flex flex-row align-items-center&quot;]/div[@class=&quot;active-site-nav d-flex flex-row list-fill-animation-7&quot;]/h2[@class=&quot;mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1&quot;]</value>
      <webElementGuid>7930658a-861a-45ba-adac-e17f1d6ed8f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/h2[2]</value>
      <webElementGuid>b15aa0f7-4b45-4d61-8379-c11737ce09b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programação'])[1]/following::h2[1]</value>
      <webElementGuid>f705ae9e-f26e-4400-bfe0-32ad44d2a9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adira'])[1]/preceding::h2[1]</value>
      <webElementGuid>a2cf2fb7-cf67-4a90-b6bd-387a8b0afafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagamento'])[1]/preceding::h2[2]</value>
      <webElementGuid>53bdc601-2bf9-4494-8d48-12fc5248621c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descobrir']/parent::*</value>
      <webElementGuid>15fbe659-3740-4450-b1ec-5b0ed029e70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[2]</value>
      <webElementGuid>f0b2e43a-679f-48b7-b738-bec66fc5d5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Descobrir' or . = 'Descobrir')]</value>
      <webElementGuid>9a9be701-7bd7-428a-a63d-1131a5f7d477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
