<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_MyDStv</name>
   <tag></tag>
   <elementGuidId>6df4d86b-2249-49cd-b803-047205fe01e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/h2[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>176d3a1f-c229-4c46-8aec-89cd72dfc6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>MyDStv</value>
      <webElementGuid>d82890e5-e5b2-4515-a00f-65163073b88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1</value>
      <webElementGuid>5aa50651-f172-4ec6-b896-ff919e1d9339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>header_top_nav</value>
      <webElementGuid>26c512af-215e-4737-82f0-83b3c45190d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-info</name>
      <type>Main</type>
      <value>{&quot;component_name&quot;:&quot;header_top_nav&quot;,&quot;component_type&quot;:&quot;links&quot;,&quot;nav_location&quot;:&quot;header&quot;,&quot;nav_item&quot;:&quot;top_level_click&quot;,&quot;nav_text&quot;:&quot;mydstv&quot;,&quot;current_page_url&quot;:&quot;https://www.dstv.com/pt-ao&quot;,&quot;target_page_url&quot;:&quot;/pt-ao/&quot;}</value>
      <webElementGuid>c238d556-2e03-4a62-b794-41c4aec1f3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MyDStv</value>
      <webElementGuid>c0fe2302-4967-4b14-92ee-45cbe80a49e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-menu-top-dark text-white position-sticky&quot;]/div[@class=&quot;container-fluid container-xl container-md&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[@class=&quot;d-flex flex-row align-items-center&quot;]/div[@class=&quot;active-site-nav d-flex flex-row list-fill-animation-7&quot;]/h2[@class=&quot;mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1&quot;]</value>
      <webElementGuid>53376224-4bdd-453a-bf88-a513a731e4c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/h2[5]</value>
      <webElementGuid>368fd1ff-be23-4d52-af0d-32b0354bdd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagamento'])[1]/following::h2[1]</value>
      <webElementGuid>971c2f1f-ade0-4f79-a515-0e1620790d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adira'])[1]/following::h2[2]</value>
      <webElementGuid>e7067c57-7cba-402f-8d55-e62730ecfd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajuda'])[1]/preceding::h2[1]</value>
      <webElementGuid>2f74053f-1b63-4457-b122-ac88ba543318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sobre'])[1]/preceding::h2[2]</value>
      <webElementGuid>82130d9a-308f-4610-b523-3ea9bed57368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MyDStv']/parent::*</value>
      <webElementGuid>0ba4164c-4e24-4963-a4c4-2b7c4966d546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[5]</value>
      <webElementGuid>9cd8ffd1-bf4e-4f79-854e-84bc83997977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'MyDStv' or . = 'MyDStv')]</value>
      <webElementGuid>cfd61693-3b73-415b-990a-073798c77528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
