<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Programao</name>
   <tag></tag>
   <elementGuidId>b667e6c3-a76a-4ff7-be34-c33e3e22ba27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.mb-0.cursor-pointer.transition-font-weight-2.bold-after.text-center.card-text.nav-inactive.font-light.blue-hover.cust-mx-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8ad082a3-f180-4d01-8cdf-c5bb5b6cb921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Programação</value>
      <webElementGuid>16fee174-7078-499d-84f7-92e08f762d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1</value>
      <webElementGuid>5c0e4ac3-a902-4217-83f4-9f0550e10d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>header_top_nav</value>
      <webElementGuid>f4f0d4fe-56ca-422c-9800-21269499503a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-info</name>
      <type>Main</type>
      <value>{&quot;component_name&quot;:&quot;header_top_nav&quot;,&quot;component_type&quot;:&quot;links&quot;,&quot;nav_location&quot;:&quot;header&quot;,&quot;nav_item&quot;:&quot;top_level_click&quot;,&quot;nav_text&quot;:&quot;programação&quot;,&quot;current_page_url&quot;:&quot;https://www.dstv.com/pt-ao&quot;,&quot;target_page_url&quot;:&quot;/pt-ao/&quot;}</value>
      <webElementGuid>a6c00851-ab2d-4a4d-a26a-15b5f4a4aa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Programação</value>
      <webElementGuid>3fc7783e-7c78-4739-b62d-bea26b95c28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-menu-top-dark text-white position-sticky&quot;]/div[@class=&quot;container-fluid container-xl container-md&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/div[@class=&quot;d-flex flex-row align-items-center&quot;]/div[@class=&quot;active-site-nav d-flex flex-row list-fill-animation-7&quot;]/h2[@class=&quot;mb-0 cursor-pointer transition-font-weight-2 bold-after text-center card-text nav-inactive font-light blue-hover cust-mx-1&quot;]</value>
      <webElementGuid>ea6a7bcd-c446-47a2-8c15-8662310632bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/h2</value>
      <webElementGuid>9099a842-2654-45e9-8e7a-3a72c78f851d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descobrir'])[1]/preceding::h2[1]</value>
      <webElementGuid>ae750aca-ea22-496f-a4d0-fee053b0a7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adira'])[1]/preceding::h2[2]</value>
      <webElementGuid>e89e5f76-da77-4e9d-b8b1-2fa70ee46d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Programação']/parent::*</value>
      <webElementGuid>729d3c50-6e07-4e94-be1d-e411c275bbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>9c09234a-5c60-494f-a8ad-f940314b9af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Programação' or . = 'Programação')]</value>
      <webElementGuid>ebb283de-5dd5-49b6-bf8c-2534b0d8d467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
