<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_API</name>
   <tag></tag>
   <elementGuidId>5f65d73f-cb55-45b6-96a3-f758c076ee4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dl_menu_deepl_api</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dl_menu_deepl_api']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4432ac38-8861-4392-85dc-027aa867d7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dl_header_menu_v2__links__item dl_navigate_away</value>
      <webElementGuid>445ba992-9516-49e2-88c3-7e7fc41475f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dl_menu_deepl_api</value>
      <webElementGuid>77b8f339-e094-4ae3-9392-f299e618ccce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pro-api?cta=header-pro-api</value>
      <webElementGuid>e39546cf-5994-495b-b1bf-934c1d9067dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            API                        </value>
      <webElementGuid>7b047e40-4b6c-4cf6-8e83-5e3fb2095771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dl_menu_deepl_api&quot;)</value>
      <webElementGuid>09e102db-f20b-4381-bae1-647524d45afe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='dl_menu_deepl_api']</value>
      <webElementGuid>764a1a3c-e908-4483-9c10-8cdca688812b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dl_navbar_desktop']/a[5]</value>
      <webElementGuid>70bcef64-5537-4e32-800d-4927c8e95944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'API')]</value>
      <webElementGuid>b3ef0afb-0c77-4332-b174-85b298356bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Porquê o DeepL?'])[1]/following::a[1]</value>
      <webElementGuid>23a2df80-e7d3-46c9-b0f9-d1e160ebbf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Business'])[1]/following::a[2]</value>
      <webElementGuid>9b2ad0b4-3682-4f1d-aedd-9b43fea98e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planos e preços'])[1]/preceding::a[1]</value>
      <webElementGuid>4b6180d0-ae83-406e-8019-097d3f643adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='API']/parent::*</value>
      <webElementGuid>5cae9744-bd31-437a-bef8-a2eebee2e2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pro-api?cta=header-pro-api')]</value>
      <webElementGuid>0f566cb2-88ba-4461-93d2-e1f19ab3e2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>8ce205f0-7655-46ad-a32e-4fd05cc4e880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'dl_menu_deepl_api' and @href = '/pro-api?cta=header-pro-api' and (text() = '
                            API                        ' or . = '
                            API                        ')]</value>
      <webElementGuid>ecd15f29-f319-4fc3-984a-9f856e02440b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
