<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Planos e preos</name>
   <tag></tag>
   <elementGuidId>baf474d1-29df-47b3-bc10-1153ff47686f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dl_menu_plans_and_pricing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dl_menu_plans_and_pricing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79f6ed2f-5466-48da-94f8-2dc21af995c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dl_header_menu_v2__links__item dl_navigate_away</value>
      <webElementGuid>3bc49fc4-c202-4e5e-9345-5b68a05dffa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dl_menu_plans_and_pricing</value>
      <webElementGuid>91ec723f-eb4c-49c7-8267-bdabc2315f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pro?cta=header-prices</value>
      <webElementGuid>9aa618fb-6a65-473c-b912-62634ba9e4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Planos e preços                        </value>
      <webElementGuid>45141c4a-3486-4317-aae5-de120fde681f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dl_menu_plans_and_pricing&quot;)</value>
      <webElementGuid>0ce9e80e-fbb7-48e4-936c-7e5a4620741c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='dl_menu_plans_and_pricing']</value>
      <webElementGuid>36e93fbd-458a-4aa1-8e44-1e9c03d91395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dl_navbar_desktop']/a[6]</value>
      <webElementGuid>f33248f0-e384-40ab-9de2-e4e8c3abc1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Planos e preços')]</value>
      <webElementGuid>bd99559c-3256-43ed-b25e-381be97da87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API'])[1]/following::a[1]</value>
      <webElementGuid>a34b0f9a-bbb0-48af-9a0f-c44c355a10b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Porquê o DeepL?'])[1]/following::a[2]</value>
      <webElementGuid>89524b46-40b2-4abe-a670-2a57088f18f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='grátis'])[1]/preceding::a[1]</value>
      <webElementGuid>9950f3aa-e763-4db6-859a-0ebd2dbbe248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Planos e preços']/parent::*</value>
      <webElementGuid>287e1eec-7424-4734-b988-61e21215cba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pro?cta=header-prices')]</value>
      <webElementGuid>19fc9ac5-7569-4986-bb6e-398bfb14eb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[6]</value>
      <webElementGuid>af5d475f-830e-489e-90fa-713804cd5ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'dl_menu_plans_and_pricing' and @href = '/pro?cta=header-prices' and (text() = '
                            Planos e preços                        ' or . = '
                            Planos e preços                        ')]</value>
      <webElementGuid>89c3c6c0-65d9-4d69-b8d8-68ae20bf0f75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
