<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reservas</name>
   <tag></tag>
   <elementGuidId>cab33cf7-bddf-4f08-96ad-707b01de8894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dnn_ibeControl_ibeControl_ucBooking_lbTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='dnn_ibeControl_ibeControl_ucBooking_lbTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72644097-edda-422d-a86d-f27c775b72a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dnn_ibeControl_ibeControl_ucBooking_lbTitle</value>
      <webElementGuid>baa269ba-c688-4f49-b37b-8a6eef3b246a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d7e52f7-a2bc-42fd-9aa5-e787dcff56fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservas</value>
      <webElementGuid>9910a374-376c-4b5f-ac82-c509c8233ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pnlIBE&quot;)/ul[@class=&quot;ibe-nav&quot;]/li[@class=&quot;active&quot;]/span[@id=&quot;dnn_ibeControl_ibeControl_ucBooking_lbTitle&quot;]</value>
      <webElementGuid>ea40fdc3-4a06-40a2-a650-aa896509f3eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='dnn_ibeControl_ibeControl_ucBooking_lbTitle']</value>
      <webElementGuid>50c4cdbf-b8a1-44a9-b77b-d700d5ecb133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlIBE']/ul/li/span[2]</value>
      <webElementGuid>7fe87e42-65fd-4801-8323-cc065378ca38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reservar já'])[4]/following::span[3]</value>
      <webElementGuid>82d64687-56fe-4e56-a308-39e68e3a691e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Económica'])[4]/following::span[3]</value>
      <webElementGuid>28f5c24d-0673-4bc5-aef4-440a7a525d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerir reservas'])[2]/preceding::span[2]</value>
      <webElementGuid>cd0460cc-5202-4276-9e79-9683281cdb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-in'])[2]/preceding::span[4]</value>
      <webElementGuid>cbcd706f-2294-4b60-9772-b3d61cbebe29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reservas']/parent::*</value>
      <webElementGuid>b08f0d74-1e35-4c97-9a20-4779206c3650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span[2]</value>
      <webElementGuid>e695370d-fdae-477c-936d-6d05805d506c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'dnn_ibeControl_ibeControl_ucBooking_lbTitle' and (text() = 'Reservas' or . = 'Reservas')]</value>
      <webElementGuid>dc1b34e2-c367-4ca6-8ad3-63dc3f7a3b2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
