<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Estado dos voos</name>
   <tag></tag>
   <elementGuidId>2b393525-e264-49af-b04b-29cd461ab20c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pnlIBE']/ul/li[4]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>35bff741-1434-4697-8297-b22908f22e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>946b8430-47c6-470b-9172-ab3c1e0ea7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Estado dos voos</value>
      <webElementGuid>dfd0504a-af85-4eb4-b655-5a899c9a759b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pnlIBE&quot;)/ul[@class=&quot;ibe-nav&quot;]/li[4]/span[@class=&quot;text&quot;]</value>
      <webElementGuid>d684c395-0ef8-4f45-bc51-ce5ad9f16ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pnlIBE']/ul/li[4]/span[2]</value>
      <webElementGuid>811ca4b2-305d-495e-b00b-7def38d3379b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-in'])[2]/following::span[2]</value>
      <webElementGuid>f7de6297-358e-4243-a58e-67a163c61bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerir reservas'])[2]/following::span[4]</value>
      <webElementGuid>b46d7f14-7de7-479e-aba9-8ea3dc8eb023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Localizador de bagagem'])[1]/preceding::span[2]</value>
      <webElementGuid>204dc6e2-e748-4fed-99a7-e04833d4ad4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reservas'])[2]/preceding::span[4]</value>
      <webElementGuid>e4cf1c68-cdf6-4a21-be92-603f54323692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Estado dos voos']/parent::*</value>
      <webElementGuid>e1039787-6711-4a29-9714-a5e76676a8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span[2]</value>
      <webElementGuid>b2037d5f-196e-43d6-8fd7-1dc0414585ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Estado dos voos' or . = 'Estado dos voos')]</value>
      <webElementGuid>ad0a92c1-2549-421b-8fce-e506a4b10d71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
