<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_COVID-19</name>
   <tag></tag>
   <elementGuidId>91c7be36-90b8-4004-b1aa-c3f471865a41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='top']/body/section[2]/div/div/a[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3967f5c-4da5-4c7b-96c0-d92b7a3e4f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-2 p-2 pull-left</value>
      <webElementGuid>1348395f-4b2d-4823-b232-5c46238d3d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ao/noticias/covid-19/</value>
      <webElementGuid>ccbeb7a0-bbc8-44e4-96d7-d869c2b1a1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COVID-19</value>
      <webElementGuid>e346ba89-3b9a-441e-b51d-c1958bc9dcc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/body[@class=&quot;noticias&quot;]/section[@class=&quot;box-noticias lista-noticias bg-light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;seccoes_&quot;]/a[@class=&quot;m-2 p-2 pull-left&quot;]</value>
      <webElementGuid>776a4752-d4d8-4f79-9a8b-2ed5b4c7be33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='top']/body/section[2]/div/div/a[7]</value>
      <webElementGuid>596cfc49-ebd1-4d77-b0ba-bc54e6e83cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'COVID-19')]</value>
      <webElementGuid>7c0b1375-2693-4711-b491-f02db9e853fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NA LENTE'])[1]/following::a[1]</value>
      <webElementGuid>c37bdbab-eb64-4e5b-b5d5-e740dc787949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sociedade'])[1]/following::a[2]</value>
      <webElementGuid>36a8ec96-7d30-420e-8379-8d3174afd9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cultura'])[1]/preceding::a[1]</value>
      <webElementGuid>22cf37dc-67ac-4f05-9cc4-2a6c195ff2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Curiosidades'])[1]/preceding::a[2]</value>
      <webElementGuid>9fc99fc1-008d-426b-86b7-40084b30afa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COVID-19']/parent::*</value>
      <webElementGuid>5fde440b-d867-43f7-a753-f220f819cb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ao/noticias/covid-19/')]</value>
      <webElementGuid>96851eaa-5536-4bcc-98ab-56921e9f346b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]</value>
      <webElementGuid>7aeab08a-373f-40bf-93c6-65e93baac315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ao/noticias/covid-19/' and (text() = 'COVID-19' or . = 'COVID-19')]</value>
      <webElementGuid>e35d4114-830d-4c2b-acbb-ec86d7c3806b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
