<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OUTROS</name>
   <tag></tag>
   <elementGuidId>bc623d42-3e12-4129-9fba-3e3259bd9c21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//html[@id='top']/body/section[2]/div/div/a[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ea4b707-94f4-4076-95e3-97ca5a9e6b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-2 p-2 pull-left</value>
      <webElementGuid>7025002f-5941-4056-b103-32fab921aa3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ao/noticias/outros/</value>
      <webElementGuid>d4ab2e93-ec00-4db3-9f7e-1aee4058fb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OUTROS</value>
      <webElementGuid>236f2235-51ca-406c-996f-350a024aa6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/body[@class=&quot;noticias&quot;]/section[@class=&quot;box-noticias lista-noticias bg-light&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;seccoes_&quot;]/a[@class=&quot;m-2 p-2 pull-left&quot;]</value>
      <webElementGuid>147b813a-54a0-437c-8cc2-08d6de91e132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='top']/body/section[2]/div/div/a[13]</value>
      <webElementGuid>39618d0c-7911-4ab4-a1de-3d7e0e0873b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'OUTROS')]</value>
      <webElementGuid>66af1651-b5e4-47d5-8789-9b522d1d916a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Política'])[1]/following::a[1]</value>
      <webElementGuid>29be7465-a6d6-4aa6-bafa-022be73e054a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desporto'])[1]/following::a[2]</value>
      <webElementGuid>90659e56-8f86-4b2a-ab0c-1b69f2f2923f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Economia'])[1]/preceding::a[1]</value>
      <webElementGuid>72433f46-1af5-4845-9c02-9ad0c3752664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Educação'])[1]/preceding::a[2]</value>
      <webElementGuid>8a1191ee-443d-4687-9e7a-8ee791c0c490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OUTROS']/parent::*</value>
      <webElementGuid>76ee4526-939c-4a0c-be46-ceea737d9509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ao/noticias/outros/')]</value>
      <webElementGuid>f537c713-7793-4d30-bddf-242af396c948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[13]</value>
      <webElementGuid>367abeb4-f246-4cd1-95c3-0aa4759cf9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ao/noticias/outros/' and (text() = 'OUTROS' or . = 'OUTROS')]</value>
      <webElementGuid>a3bcb220-b974-4647-bca4-4d027da85047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
