<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Torne-se um anfitrio</name>
   <tag></tag>
   <elementGuidId>bc735287-34cf-49a9-a966-a5edad99626b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._tzure7u > div._lvb55za</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-application']/div/div/div/header/div/div/div[3]/div/div/nav/ul/li[3]/div/div/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9113bc9-2d4a-4bde-af0e-78f63164dac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_lvb55za</value>
      <webElementGuid>5cdd8553-82b5-4e74-a2a3-945c7642c46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Torne-se um anfitrião</value>
      <webElementGuid>3851acc4-3c69-420c-8932-2aba60b845c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-application&quot;)/div[1]/div[@class=&quot;t1bgcr6e&quot;]/div[1]/header[@class=&quot;_8iqo2b&quot;]/div[@class=&quot;_xi61peg&quot;]/div[@class=&quot;_hgs47m&quot;]/div[@class=&quot;_ni9axhe&quot;]/div[1]/div[@class=&quot;_cfvh61&quot;]/nav[1]/ul[@class=&quot;_1s04l2o&quot;]/li[@class=&quot;_1g2dfiu&quot;]/div[1]/div[@class=&quot;_e296pg&quot;]/button[@class=&quot;_1nb1naqj&quot;]/div[@class=&quot;_tzure7u&quot;]/div[@class=&quot;_lvb55za&quot;]</value>
      <webElementGuid>6d98b51b-1a32-4862-b836-e5bcb5839cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-application']/div/div/div/header/div/div/div[3]/div/div/nav/ul/li[3]/div/div/button/div/div</value>
      <webElementGuid>6223d5cc-d0b0-418b-9fac-c78cb67cb721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escolha uma moeda:'])[1]/following::div[4]</value>
      <webElementGuid>d7c6b178-0089-433b-97c1-f9ff9511257b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajuda'])[1]/preceding::div[1]</value>
      <webElementGuid>3e4f161e-10e0-4fb4-aaec-5e5316fb3a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastrar-se'])[1]/preceding::div[5]</value>
      <webElementGuid>c1a5f5fc-8ea1-4f5f-90c8-0ea9971e9be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Torne-se um anfitrião']/parent::*</value>
      <webElementGuid>2e532fda-742b-4bd0-a07e-491921ad4041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/button/div/div</value>
      <webElementGuid>f80bd722-9d55-4abc-8563-63db7b803a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Torne-se um anfitrião' or . = 'Torne-se um anfitrião')]</value>
      <webElementGuid>125bad40-76f0-4c40-9fa1-6c88266cd471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
