<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ajuda</name>
   <tag></tag>
   <elementGuidId>2c92ee55-56ca-4b99-b926-f0f4d144ff27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='help-center-link']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._tzure7u > div._lvb55za</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4e49e2d-1432-40b8-8784-aca1ab1be130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_lvb55za</value>
      <webElementGuid>69f7f56c-53fe-430a-9072-04b4e512ad2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ajuda</value>
      <webElementGuid>9134f59f-2b94-4e7d-8336-2d12e31339ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;help-center-link&quot;)/div[@class=&quot;_tzure7u&quot;]/div[@class=&quot;_lvb55za&quot;]</value>
      <webElementGuid>5a7e817f-5e26-4a4d-b585-2c3426f8a478</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='help-center-link']/div/div</value>
      <webElementGuid>d7d8183f-0f73-448f-a1bb-25a6bd050cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Torne-se um anfitrião'])[1]/following::div[4]</value>
      <webElementGuid>3e09280c-c05e-4029-81bf-77404846040b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escolha uma moeda:'])[1]/following::div[8]</value>
      <webElementGuid>0d94dff2-34a5-4f6a-af83-d814805ed290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cadastrar-se'])[1]/preceding::div[1]</value>
      <webElementGuid>698fe4a4-06be-4b6d-8bbb-02084cb4109c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar'])[1]/preceding::div[5]</value>
      <webElementGuid>cde2cb96-cf60-44ad-afd5-b3ef8ed8d03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ajuda']/parent::*</value>
      <webElementGuid>f0459b9c-445a-42ab-a442-44682569709f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/a/div/div</value>
      <webElementGuid>96258ec0-3db0-4b4f-834b-e6c7b924d099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ajuda' or . = 'Ajuda')]</value>
      <webElementGuid>ebff41fa-7f73-42d4-8b15-54929a3bb87b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
