<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Para comear, adicione seu email profissional_work-email</name>
   <tag></tag>
   <elementGuidId>5a073b68-3718-4b29-a19e-fdd45e7d89c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#work-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='work-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>813813bf-19ca-47c1-ba3e-40f2ed310834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1dff7f46 focus-visible</value>
      <webElementGuid>2e47f535-2c82-4962-bf5e-5f02cf2e409a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>work-email</value>
      <webElementGuid>9a8616fb-c857-4836-b45d-e178faf5d18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>work-email</value>
      <webElementGuid>55ea1179-62d7-49aa-b63f-8f2bbb9254a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90b7ebec-8394-4071-bb14-8046ff9a22c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work-email&quot;)</value>
      <webElementGuid>c74a43e6-d847-469a-8fe6-c9c4bca6d9f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='work-email']</value>
      <webElementGuid>a6b6c72e-03f7-4bf4-8dd7-950930175cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-application']/div/div/div/main/div/div/section/div/div/div[2]/div/div/div/div[3]/form/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>a6a747f8-051b-4c37-bd74-5a5aa86f8623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>968524dc-3bbd-4b7c-8c3c-40b9af1d0e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'work-email' and @name = 'work-email' and @type = 'text']</value>
      <webElementGuid>44c6a031-a354-4af1-90bb-5d96ec342eb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
