<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Para comear, adicione seu email profissional_work-email</name>
   <tag></tag>
   <elementGuidId>93c57943-6f0b-4007-bf3c-1297571adfce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#work-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='work-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>454fdc9c-757f-443f-a41c-2534ea8737ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1dff7f46 focus-visible</value>
      <webElementGuid>2794492d-b5b8-4f03-b221-972e2c206956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>work-email</value>
      <webElementGuid>3093b6f4-6c9c-426b-b83d-17a4c6c37f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>work-email</value>
      <webElementGuid>bd620751-2687-44a9-b570-269fc8274aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14f7976a-cfc6-4eb9-bd91-8558f5fe9abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;work-email&quot;)</value>
      <webElementGuid>68fba876-be01-40ce-bb58-9dd3c63ed4e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='work-email']</value>
      <webElementGuid>b8fc4693-025f-4a15-8078-627be66234ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-application']/div/div/div/main/div/div/section/div/div/div[2]/div/div/div/div[3]/form/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>186bfb6f-9861-4f4d-ad71-e450bc65f8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4578ca09-5ef3-4beb-88b7-379770266144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'work-email' and @name = 'work-email' and @type = 'text']</value>
      <webElementGuid>0246bea2-63c1-4cdf-b25f-034be8bc4c7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
