<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DESTAQUES</name>
   <tag></tag>
   <elementGuidId>dbc7cb99-8498-40d4-9f6a-1deb4fd3740d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a.page02</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cabecera_']/div[4]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4cdf5dc1-1364-48b8-ae05-4df46dcccfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page02</value>
      <webElementGuid>4c9d138e-66f8-43f5-b913-63536b36883c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/destaques/</value>
      <webElementGuid>06424744-7c6f-4ff9-b800-1131332ff6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DESTAQUES</value>
      <webElementGuid>aea93f8f-0aaf-4c7c-abe2-db4fd27f9c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cabecera_&quot;)/div[@class=&quot;menu&quot;]/ul[1]/li[4]/a[@class=&quot;page02&quot;]</value>
      <webElementGuid>e75d7954-cdee-4cd0-aee4-24a3dfc851dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cabecera_']/div[4]/ul/li[4]/a</value>
      <webElementGuid>c0a0031e-e664-466e-8ed1-e13dc6f78ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DESTAQUES')]</value>
      <webElementGuid>9658f001-9f9d-4a9e-b873-d4e37ba82dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GUIA TV'])[1]/following::a[1]</value>
      <webElementGuid>e7e31e15-af6b-45e5-8600-e221d858675f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/following::a[2]</value>
      <webElementGuid>b6f23c96-447f-4713-b3e4-746b39507107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PASSATEMPOS'])[1]/preceding::a[1]</value>
      <webElementGuid>12aa9554-f073-4f7d-8722-af173ab10608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Flash T4'])[1]/preceding::a[9]</value>
      <webElementGuid>028b6705-48cd-478a-b63a-6b599eaab320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DESTAQUES']/parent::*</value>
      <webElementGuid>4671bff7-95a6-4408-8d48-6ae137b8037b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/destaques/')]</value>
      <webElementGuid>2f205ab5-0ee2-4a83-848d-5db0eab987f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[4]/a</value>
      <webElementGuid>40826c76-7804-4aff-9d71-4b201486083d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/destaques/' and (text() = 'DESTAQUES' or . = 'DESTAQUES')]</value>
      <webElementGuid>b66afbf0-05cf-48d6-b3a1-48032a5a843b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
