<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HOME</name>
   <tag></tag>
   <elementGuidId>bef1b00b-ed6f-469c-93e7-30b785cb7f28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a.home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cabecera_']/div[4]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a12baa2-074d-4e3a-aa1c-ada83f0536a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>8604f884-020c-4762-a19a-b9303abce76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>4c379017-e450-4366-bdc0-713bfd9a043c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOME</value>
      <webElementGuid>19da3e2a-a8df-4475-9d10-3271896a8fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cabecera_&quot;)/div[@class=&quot;menu&quot;]/ul[1]/li[2]/a[@class=&quot;home&quot;]</value>
      <webElementGuid>7ae2185a-c9c2-447c-a0f9-7195a57969a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cabecera_']/div[4]/ul/li[2]/a</value>
      <webElementGuid>e46c8ef2-9ad1-4c5d-a3ba-51a91ebb6913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HOME')]</value>
      <webElementGuid>b6e3db35-359a-4d52-9cdd-bf50742b1196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUTUBE'])[1]/following::a[2]</value>
      <webElementGuid>d4b20389-bb6b-40c8-8fd9-b57a289cc22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TWITTER'])[1]/following::a[3]</value>
      <webElementGuid>d8e58e8c-304c-4af0-b1c0-274d782cf6db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GUIA TV'])[1]/preceding::a[1]</value>
      <webElementGuid>81dfac2a-9930-49d1-aead-abc1099b139b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESTAQUES'])[1]/preceding::a[2]</value>
      <webElementGuid>b06aefe8-ed34-40f3-9ac4-6a52a75e66e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HOME']/parent::*</value>
      <webElementGuid>d13d226d-2cfd-47f2-82a7-a325ad48c4ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[8]</value>
      <webElementGuid>78c3306f-f3db-4cb3-b831-6c310e223126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li[2]/a</value>
      <webElementGuid>bbad96a7-0324-4e7b-b156-2cf78d57eb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'HOME' or . = 'HOME')]</value>
      <webElementGuid>a507955e-3b92-434a-b0b8-656dbd2979ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
