<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PASSATEMPOS</name>
   <tag></tag>
   <elementGuidId>b21b5c8c-3ec7-4c22-9682-cc2a4fea8878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a.page03</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cabecera_']/div[4]/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d991c82f-d57c-4818-b46b-b63ee9190250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page03</value>
      <webElementGuid>a49c06b0-d8bd-4dce-91ef-56d7d2acd723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/passatempos/</value>
      <webElementGuid>748d5ac4-c356-44c2-ae0b-ecb2e9f90293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PASSATEMPOS</value>
      <webElementGuid>1aeef7b5-7680-4d36-a10e-dae73753adfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cabecera_&quot;)/div[@class=&quot;menu&quot;]/ul[1]/li[5]/a[@class=&quot;page03&quot;]</value>
      <webElementGuid>09d4f263-f07e-4044-a1a6-58355904efc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cabecera_']/div[4]/ul/li[5]/a</value>
      <webElementGuid>980821ff-95cf-4cd8-951c-de35ef7cced4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PASSATEMPOS')]</value>
      <webElementGuid>c4aa9917-afbb-4b84-aa90-a4dbd06beb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESTAQUES'])[1]/following::a[1]</value>
      <webElementGuid>cb53ba9f-730e-41d4-baee-a3ff4c92db80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GUIA TV'])[1]/following::a[2]</value>
      <webElementGuid>79ab57d6-36c4-4b6d-bd3b-a334b193986b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Flash T4'])[1]/preceding::a[8]</value>
      <webElementGuid>915c020c-2132-4a00-9668-28ed92335447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MÁS INFO'])[1]/preceding::a[9]</value>
      <webElementGuid>c8cf1619-3d7b-420a-87e8-d1c473ef1510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PASSATEMPOS']/parent::*</value>
      <webElementGuid>41227e55-a8fd-4231-8dac-39ccb6a32565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/passatempos/')]</value>
      <webElementGuid>d3a0380f-da32-412a-9225-34f70e5d65d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>50818628-421b-4851-b291-38369f1f15a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/passatempos/' and (text() = 'PASSATEMPOS' or . = 'PASSATEMPOS')]</value>
      <webElementGuid>d9df9150-946a-4912-9239-33345b49de9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
