<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Appliances</name>
   <tag></tag>
   <elementGuidId>0d77863c-8f6e-43e2-bf5c-e59881075e30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='component-id']/div[2]/div[4]/ul/li[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d0bb13e-5029-474c-b8cb-8a0781d21609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nv00-gnb__l0-menu-btn</value>
      <webElementGuid>17245760-f9fa-4b15-9b7c-3e08551a0993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>e635f0cd-d0d9-49db-ab7e-d35b2aa3dd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b8c2266-72fb-456c-9484-928fd6babf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d624b4a-66ba-4764-a867-b5ed504ba6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-tr</name>
      <type>Main</type>
      <value>nv00_gnb-1depth-navigation2</value>
      <webElementGuid>fd72abd9-799a-4aef-a3fc-d35c3e8016b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ca</name>
      <type>Main</type>
      <value>navigation</value>
      <webElementGuid>64671201-a2a1-463c-bf04-8fe5cc811ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-ac</name>
      <type>Main</type>
      <value>gnb</value>
      <webElementGuid>5a14373c-bffd-43e6-b404-3aa785726bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>an-la</name>
      <type>Main</type>
      <value>Appliances</value>
      <webElementGuid>9dc1db53-1775-41ee-a435-4a27db8bfab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Appliances
          
              
          
        </value>
      <webElementGuid>9671a5a5-b908-4b73-bdd8-1028e8582eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-id&quot;)/div[@class=&quot;nv00-gnb__inner-wrap&quot;]/div[@class=&quot;nv00-gnb__l0-menu-wrap&quot;]/ul[@class=&quot;nv00-gnb__l0-menu-list left-menu&quot;]/li[@class=&quot;nv00-gnb__l0-menu&quot;]/button[@class=&quot;nv00-gnb__l0-menu-btn&quot;]</value>
      <webElementGuid>13e086f3-69b5-4945-a823-411e08485797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='component-id']/div[2]/div[4]/ul/li[3]/button</value>
      <webElementGuid>4a92ee95-5ed4-45d8-8ed4-4369bd0b7b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Audio Accessories'])[1]/following::button[1]</value>
      <webElementGuid>66814677-846a-40c9-a7c3-ee7e0138613b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TV Accessories'])[1]/following::button[1]</value>
      <webElementGuid>60557b78-2778-4a91-80fb-cf747847626a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bespoke'])[1]/preceding::button[1]</value>
      <webElementGuid>b41dd97c-524e-4d27-819e-165dbb0b0e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bespoke Home'])[1]/preceding::button[2]</value>
      <webElementGuid>c1754246-749b-43c2-a5de-e706ffa2ac49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Appliances']/parent::*</value>
      <webElementGuid>8db4113b-9f54-409f-aa72-7a23cf3cd258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/button</value>
      <webElementGuid>92c49648-f998-41ee-b0f6-d80cf6cf758f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
          Appliances
          
              
          
        ' or . = '
          Appliances
          
              
          
        ')]</value>
      <webElementGuid>79bbe0a4-9ca6-4cb9-825b-fa741390aff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
